<?php

declare(strict_types=1);

use Copot\Core\Config;
use Copot\Core\Database;
use Copot\Core\Env;
use Copot\Core\InstallerSchemaRunner;
use Copot\Core\ModuleDiscovery;
use Copot\Core\ModuleManager;
use Copot\Core\ModuleRepository;

$base=dirname(__DIR__);chdir($base);require $base.'/bootstrap/autoload.php';Env::load($base.'/.env');$assertions=0;$assert=static function(bool $ok,string $message)use(&$assertions):void{$assertions++;if(!$ok)throw new RuntimeException($message);};$host=(string)Env::get('DB_HOST','127.0.0.1');$port=(int)Env::get('DB_PORT',3306);$username=(string)Env::get('DB_USERNAME','root');$password=(string)Env::get('DB_PASSWORD','');$server=new PDO("mysql:host={$host};port={$port};charset=utf8mb4",$username,$password,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$names=[];$create=static function(string $prefix)use(&$names,$server):string{$name=$prefix.bin2hex(random_bytes(6));$names[]=$name;$server->exec('CREATE DATABASE `'.$name.'` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');return $name;};$install=static function(string $name)use($base,$host,$port,$username,$password):Database{$_ENV['DB_DATABASE']=$name;putenv('DB_DATABASE='.$name);(new InstallerSchemaRunner($base.'/database/schema.sql'))->install(['host'=>$host,'port'=>$port,'database'=>$name,'username'=>$username,'password'=>$password]);return new Database(new Config($base.'/config'));};
try{
 $fresh=$create('copot_m311_wu4_fresh_');$freshDb=$install($fresh);$connection=$freshDb->connection();$assert((int)$connection->query("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='form_submission_attempts'")->fetchColumn()===1,'Fresh schema omitted rate-limit attempts.');$assert((int)$connection->query("SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='form_submission_attempts' AND column_name IN ('id','form_id','client_address','attempted_at')")->fetchColumn()===4,'Rate-limit table columns are incomplete.');$manager=new ModuleManager(new ModuleDiscovery($base.'/modules'),new ModuleRepository($freshDb));$manager->install('form-manager');$manager->enable('form-manager');$assert($connection->query("SELECT status FROM modules WHERE name='form-manager'")->fetchColumn()==='enabled','Form Manager lifecycle did not enable.');$manifest=require $base.'/build/package_manifest.php';$assert(in_array('modules/form-manager',$manifest['include']??[],true)&&in_array('database',$manifest['include']??[],true),'Package manifest omitted WU4 production ownership.');
 $legacy=$create('copot_m311_wu4_upgrade_');$legacyDb=$install($legacy);$legacyConnection=$legacyDb->connection();$legacyConnection->exec('DROP TABLE form_submission_attempts');$upgrade=(string)file_get_contents($base.'/database/upgrades/m3_11_form_manager.sql');foreach(array_filter(array_map('trim',explode(';',$upgrade)))as$statement){$legacyConnection->exec($statement);$legacyConnection->exec($statement);} $assert((int)$legacyConnection->query("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='form_submission_attempts'")->fetchColumn()===1,'Existing-install upgrade did not converge rate-limit table.');$assert((int)$legacyConnection->query("SELECT COUNT(DISTINCT index_name) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='form_submission_attempts' AND index_name='idx_form_submission_attempts_form_client_time'")->fetchColumn()===1,'Rate-limit lookup index did not converge.');$assert((int)$legacyConnection->query("SELECT COUNT(DISTINCT index_name) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='form_submission_attempts' AND index_name='idx_form_submission_attempts_cleanup'")->fetchColumn()===1,'Rate-limit cleanup index did not converge.');
 echo "M3.11 WU4 closure passed ({$assertions} assertions).\n";
}finally{foreach($names as$name)$server->exec('DROP DATABASE IF EXISTS `'.$name.'`');}
