<?php

declare(strict_types=1);

use Copot\Core\Config;
use Copot\Core\Database;
use Copot\Core\Env;
use Copot\Core\InstallerSchemaRunner;
use Copot\Core\ModuleDiscovery;
use Copot\Core\ModuleManager;
use Copot\Core\ModuleRepository;

$basePath=dirname(__DIR__);chdir($basePath);require $basePath.'/bootstrap/autoload.php';Env::load($basePath.'/.env');
$assertions=0;$assert=static function(bool $condition,string $message)use(&$assertions):void{$assertions++;if(!$condition)throw new RuntimeException($message);};
$host=(string)Env::get('DB_HOST','127.0.0.1');$port=(int)Env::get('DB_PORT','3306');$username=(string)Env::get('DB_USERNAME','root');$password=(string)Env::get('DB_PASSWORD','');$server=new PDO("mysql:host={$host};port={$port};charset=utf8mb4",$username,$password,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$names=[];
$databaseName=static function(string $prefix)use(&$names):string{$name=$prefix.bin2hex(random_bytes(6));$names[]=$name;return $name;};$create=static function(string $name)use($server):void{$server->exec('CREATE DATABASE `'.$name.'` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');};
$execute=static function(PDO $connection,string $sql):void{foreach(array_filter(array_map('trim',preg_split('/;\s*(?:\R|$)/',$sql)?:[]))as $statement)$connection->exec($statement);};
$configFor=static function(string $name)use($basePath,$host,$port,$username,$password):Config{$config=new Config($basePath.'/config');$reflection=new ReflectionClass($config);$items=$reflection->getProperty('items');$items->setAccessible(true);$configured=$items->getValue($config);foreach(['host'=>$host,'port'=>$port,'database'=>$name,'username'=>$username,'password'=>$password]as$key=>$value)$configured['database']['connections']['mysql'][$key]=$value;$items->setValue($config,$configured);return $config;};
try {
    $fresh=$databaseName('copot_m311_fresh_');$create($fresh);(new InstallerSchemaRunner($basePath.'/database/schema.sql'))->install(['host'=>$host,'port'=>$port,'database'=>$fresh,'username'=>$username,'password'=>$password]);$connection=(new Database($configFor($fresh)))->connection();
    foreach(['forms','form_fields','form_field_options','form_submissions','form_submission_values']as$table)$assert((int)$connection->query('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='.$connection->quote($table))->fetchColumn()===1,'Fresh schema creates '.$table.'.');
    $columns=[];foreach($connection->query("SELECT table_name,column_name FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name IN ('forms','form_fields','form_field_options','form_submissions','form_submission_values')")as$row)$columns[$row['table_name'].'.'.$row['column_name']]=true;foreach(['forms.name','forms.status','form_fields.field_key','form_fields.is_required','form_field_options.option_value','form_submissions.status','form_submission_values.field_label','form_submission_values.value_label']as$column)$assert(isset($columns[$column]),'Fresh schema contains '.$column.'.');
    foreach(['uq_form_fields_form_key','uq_form_fields_form_order','uq_form_field_options_order','uq_form_submission_values_submission_key','idx_forms_status_updated','idx_form_submissions_form_status_updated','idx_form_submission_values_submission','idx_form_submission_values_field']as$key)$assert((int)$connection->query('SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=DATABASE() AND index_name='.$connection->quote($key))->fetchColumn()>0,'Fresh schema contains '.$key.'.');
    foreach(['fk_form_fields_form','fk_form_field_options_field','fk_form_submissions_form','fk_form_submission_values_submission','fk_form_submission_values_field']as$key)$assert((int)$connection->query('SELECT COUNT(*) FROM information_schema.referential_constraints WHERE constraint_schema=DATABASE() AND constraint_name='.$connection->quote($key))->fetchColumn()===1,'Fresh schema contains '.$key.'.');
    $permissions=['forms.view','forms.manage','forms.submissions.view','forms.submissions.delete'];foreach($permissions as$permission){$assert((int)$connection->query('SELECT COUNT(*) FROM permissions WHERE slug='.$connection->quote($permission))->fetchColumn()===1,'Fresh permission is present once.');$assert((int)$connection->query("SELECT COUNT(*) FROM role_permissions rp INNER JOIN roles r ON r.id=rp.role_id INNER JOIN permissions p ON p.id=rp.permission_id WHERE r.slug='admin' AND p.slug=".$connection->quote($permission))->fetchColumn()===1,'Administrator grant is present once.');}
 $manager=new ModuleManager(new ModuleDiscovery($basePath.'/modules'),new ModuleRepository(new Database($configFor($fresh))));$definitions=[];foreach($manager->discover()as$definition)$definitions[$definition->name()]=$definition;$assert(isset($definitions['form-manager'])&&$definitions['form-manager']->routes()==='routes.php','Form Manager manifest is discoverable with its bounded public/Admin routes.');$manager->install('form-manager');$manager->enable('form-manager');$assert((string)$connection->query("SELECT status FROM modules WHERE name='form-manager'")->fetchColumn()==='enabled','Module Manager enables Form Manager.');$manager->disable('form-manager');$assert((string)$connection->query("SELECT status FROM modules WHERE name='form-manager'")->fetchColumn()==='disabled','Module Manager disables Form Manager.');
    $legacy=$databaseName('copot_m311_legacy_');$create($legacy);$legacyConnection=new PDO("mysql:host={$host};port={$port};dbname={$legacy};charset=utf8mb4",$username,$password,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$execute($legacyConnection,(string)file_get_contents($basePath.'/tests/fixtures/m3_10_pre_form_manager.sql'));$upgrade=(string)file_get_contents($basePath.'/database/upgrades/m3_11_form_manager.sql');$execute($legacyConnection,$upgrade);$execute($legacyConnection,$upgrade);foreach(['forms','form_fields','form_field_options','form_submissions','form_submission_values']as$table)$assert((int)$legacyConnection->query('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='.$legacyConnection->quote($table))->fetchColumn()===1,'Two-pass upgrade creates '.$table.'.');foreach($permissions as$permission)$assert((int)$legacyConnection->query('SELECT COUNT(*) FROM permissions WHERE slug='.$legacyConnection->quote($permission))->fetchColumn()===1,'Two-pass upgrade provisions permission once.');$assert((int)$legacyConnection->query("SELECT COUNT(*) FROM role_permissions rp INNER JOIN roles r ON r.id=rp.role_id INNER JOIN permissions p ON p.id=rp.permission_id WHERE r.slug='admin' AND p.slug LIKE 'forms.%'")->fetchColumn()===4,'Two-pass upgrade provisions Administrator grants once.');
    $manifest=require $basePath.'/build/package_manifest.php';$assert(in_array('modules/form-manager',$manifest['include']??[],true),'Package manifest includes Form Manager.');$finalizer=(string)file_get_contents($basePath.'/app/Core/InstallerFinalizer.php');$assert(str_contains($finalizer,"'form-manager'"),'Fresh-install baseline activates Form Manager.');
    echo "M3.11 WU1 form provisioning passed ({$assertions} assertions).\n";
}finally{foreach($names as$name)$server->exec('DROP DATABASE IF EXISTS `'.$name.'`');}
