<?php

declare(strict_types=1);

use Copot\Core\Application;
use Copot\Core\Config;
use Copot\Core\Database;
use Copot\Core\Env;
use Copot\Core\InstallerSchemaRunner;
use Copot\Core\Request;
use Copot\Core\Response;

$basePath=dirname(__DIR__);chdir($basePath);session_save_path(sys_get_temp_dir());session_id('copotm311wu2'.bin2hex(random_bytes(5)));require $basePath.'/bootstrap/autoload.php';Env::load($basePath.'/.env');
$assertions=0;$assert=static function(bool $condition,string $message)use(&$assertions):void{$assertions++;if(!$condition)throw new RuntimeException($message);};$property=static fn(Response $response,string $name):mixed=>(new ReflectionProperty(Response::class,$name))->getValue($response);$status=static fn(Response $response):int=>(int)$property($response,'status');$content=static fn(Response $response):string=>(string)$property($response,'content');$location=static fn(Response $response):?string=>$property($response,'headers')['Location']??null;
$host=(string)Env::get('DB_HOST','127.0.0.1');$port=(int)Env::get('DB_PORT',3306);$username=(string)Env::get('DB_USERNAME','root');$password=(string)Env::get('DB_PASSWORD','');$databaseName='copot_m311_wu2_'.bin2hex(random_bytes(6));$quoted='`'.$databaseName.'`';$server=new PDO("mysql:host={$host};port={$port};charset=utf8mb4",$username,$password,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$server->exec('CREATE DATABASE '.$quoted.' CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
try{
 (new InstallerSchemaRunner($basePath.'/database/schema.sql'))->install(['host'=>$host,'port'=>$port,'database'=>$databaseName,'username'=>$username,'password'=>$password]);$_ENV['DB_DATABASE']=$databaseName;putenv('DB_DATABASE='.$databaseName);$database=new Database(new Config($basePath.'/config'));$connection=$database->connection();$connection->exec("INSERT INTO modules (name,title,version,path,status,installed_at,created_at,updated_at) VALUES ('form-manager','Form Manager','0.1.0','modules/form-manager','enabled',NOW(),NOW(),NOW())");
 $hash=password_hash('form-password',PASSWORD_DEFAULT);$connection->prepare("INSERT INTO users(name,email,password_hash,status,created_at,updated_at)VALUES('Form Administrator','forms@example.test',:hash,'active',NOW(),NOW())")->execute(['hash'=>$hash]);$userId=(int)$connection->lastInsertId();$connection->prepare("INSERT INTO user_roles(user_id,role_id) SELECT :user,id FROM roles WHERE slug='admin'")->execute(['user'=>$userId]);$connection->prepare("INSERT INTO roles(name,slug,created_at,updated_at)VALUES('Form denied','form-denied',NOW(),NOW())")->execute();$deniedRole=(int)$connection->lastInsertId();$connection->prepare("INSERT INTO users(name,email,password_hash,status,created_at,updated_at)VALUES('Denied forms','forms-denied@example.test',:hash,'active',NOW(),NOW())")->execute(['hash'=>password_hash('denied-password',PASSWORD_DEFAULT)]);$denied=(int)$connection->lastInsertId();$connection->prepare('INSERT INTO user_roles(user_id,role_id)VALUES(:user,:role)')->execute(['user'=>$denied,'role'=>$deniedRole]);$connection->prepare("INSERT INTO role_permissions(role_id,permission_id) SELECT :role,id FROM permissions WHERE slug='admin.access'")->execute(['role'=>$deniedRole]);
 $app=new Application($basePath);$app->session()->start();require $basePath.'/routes/web.php';require $basePath.'/routes/auth.php';require $basePath.'/routes/admin.php';$app->moduleLoader()->loadResolvers($app);$app->moduleLoader()->loadRoutes($app);require $basePath.'/routes/admin_fallback.php';$path=$app->adminUrl()->childUrl('forms');$assert($app->auth()->attempt('forms@example.test','form-password'),'Administrator authentication failed.');$csrf=$app->session()->csrfToken();
 $list=$app->router()->dispatch(new Request('GET',$path));$html=$content($list);$assert($status($list)===200&&str_contains($html,'Forms')&&str_contains($html,'Create Form'),'Form workspace did not render.');$assert(str_contains($html,'name="q"'),'Workspace omitted filter controls.');$assert(str_contains($html,'View submissions')&&str_contains($html,$path.'/submissions'),'Authorized submission-workspace link or configured Admin path was omitted.');$assert(str_contains($html,'Forms')&&str_contains($html,$path.'/create'),'Navigation or configured Admin path was omitted.');
 $createGet=$app->router()->dispatch(new Request('GET',$path.'/create'));$createHtml=$content($createGet);$assert($status($createGet)===200&&str_contains($createHtml,'<fieldset')&&str_contains($createHtml,'Add field'),'Create page omitted structured field editor.');$assert(str_contains($createHtml,'Removing a field changes the current form definition'),'Create page omitted history guidance.');
 $field=['field_key'=>'email','label'=>'Email','field_type'=>'email','sort_order'=>'0','is_required'=>'1','min_length'=>'','max_length'=>'190','options'=>[]];$created=$app->router()->dispatch(new Request('POST',$path,[],['_token'=>$csrf,'name'=>'Contact form','fields'=>[$field]]));$assert($status($created)===302&&$location($created)===$path.'?notice=created','Form create did not use PRG.');$id=(int)$connection->query("SELECT id FROM forms WHERE name='Contact form'")->fetchColumn();$assert($id>0&&(int)$connection->query("SELECT COUNT(*) FROM form_fields WHERE form_id={$id}")->fetchColumn()===1,'Create did not persist the complete definition.');$populatedList=$app->router()->dispatch(new Request('GET',$path,['q'=>'Contact','status'=>'draft','page'=>'1','per_page'=>'101']));$assert($status($populatedList)===200&&str_contains($content($populatedList),'data-label="Name"')&&str_contains($content($populatedList),'Contact form'),'Workspace omitted responsive deterministic list rows.');
 $invalid=$app->router()->dispatch(new Request('POST',$path,[],['_token'=>$csrf,'name'=>'<x>','fields'=>['broken']]));$assert($status($invalid)===422&&str_contains($content($invalid),'&lt;x&gt;')&&!str_contains($content($invalid),'<x>')&&str_contains($content($invalid),'aria-live="assertive"'),'Malformed structured rows were not safely rejected and repopulated.');$noCsrf=$app->router()->dispatch(new Request('POST',$path,[],['name'=>'Blocked','fields'=>[]]));$assert($status($noCsrf)===419,'Create did not require CSRF.');
 $edit=$app->router()->dispatch(new Request('GET',$path.'/'.$id.'/edit'));preg_match('/name="expected_updated_at" value="([^"]+)"/',$content($edit),$match);$expected=html_entity_decode((string)($match[1]??''),ENT_QUOTES,'UTF-8');$assert($status($edit)===200&&$expected!==''&&str_contains($content($edit),'Field key'),'Edit page omitted definition/concurrency fields.');$updated=$app->router()->dispatch(new Request('POST',$path.'/'.$id.'/edit',[],['_token'=>$csrf,'expected_updated_at'=>$expected,'name'=>'Contact form updated','fields'=>[array_merge($field,['label'=>'Email address'])]]));$assert($status($updated)===302&&$location($updated)===$path.'?notice=updated','Form update did not use PRG.');$assert($connection->query("SELECT name FROM forms WHERE id={$id}")->fetchColumn()==='Contact form updated','Full definition update did not persist metadata.');
 $stale=$app->router()->dispatch(new Request('POST',$path.'/'.$id.'/edit',[],['_token'=>$csrf,'expected_updated_at'=>$expected,'name'=>'Stale','fields'=>[$field]]));$assert($status($stale)===422&&str_contains($content($stale),'changed elsewhere'),'Stale update was not controlled.');
 $publish=$app->router()->dispatch(new Request('POST',$path.'/'.$id.'/publish',[],['_token'=>$csrf]));$assert($status($publish)===302&&$connection->query("SELECT status FROM forms WHERE id={$id}")->fetchColumn()==='published','Draft publish transition failed.');$disable=$app->router()->dispatch(new Request('POST',$path.'/'.$id.'/disable',[],['_token'=>$csrf]));$assert($status($disable)===302&&$connection->query("SELECT status FROM forms WHERE id={$id}")->fetchColumn()==='disabled','Disable transition failed.');$reverse=$app->router()->dispatch(new Request('POST',$path.'/'.$id.'/publish',[],['_token'=>$csrf]));$assert($status($reverse)===422,'Disabled reverse transition was not rejected.');
 $connection->exec("INSERT INTO forms(name,status,created_at,updated_at)VALUES('Retained form','disabled',NOW(),NOW())");$retainedId=(int)$connection->lastInsertId();$connection->exec("INSERT INTO form_submissions(form_id,status,created_at,updated_at)VALUES({$retainedId},'new',NOW(),NOW())");$retainedList=$app->router()->dispatch(new Request('GET',$path));$assert(str_contains($content($retainedList),'This form has retained submissions and cannot be deleted. Disable it instead.'),'Retained-submission delete guidance was omitted.');$retainedDelete=$app->router()->dispatch(new Request('POST',$path.'/'.$retainedId.'/delete',[],['_token'=>$csrf]));$assert($status($retainedDelete)===302&&str_contains((string)$location($retainedDelete),'error=')&&(int)$connection->query("SELECT COUNT(*) FROM forms WHERE id={$retainedId}")->fetchColumn()===1,'Retained-submission delete was not rejected.');
 $delete=$app->router()->dispatch(new Request('POST',$path.'/'.$id.'/delete',[],['_token'=>$csrf]));$assert($status($delete)===302&&(int)$connection->query("SELECT COUNT(*) FROM forms WHERE id={$id}")->fetchColumn()===0,'Permanent deletion without submissions failed.');$missing=$app->router()->dispatch(new Request('GET',$path.'/999999/edit'));$assert($status($missing)===404,'Unknown form did not return 404.');
 $app->auth()->logout();$guest=$app->router()->dispatch(new Request('POST',$path,[],['_token'=>'bad']));$assert($status($guest)===302,'Guest mutation did not redirect to Admin login.');$connection->prepare("INSERT INTO roles(name,slug,created_at,updated_at)VALUES('Forms viewer','forms-viewer',NOW(),NOW())")->execute();$viewerRole=(int)$connection->lastInsertId();$connection->prepare("INSERT INTO users(name,email,password_hash,status,created_at,updated_at)VALUES('Forms viewer','forms-viewer@example.test',:hash,'active',NOW(),NOW())")->execute(['hash'=>password_hash('viewer-password',PASSWORD_DEFAULT)]);$viewer=(int)$connection->lastInsertId();$connection->prepare('INSERT INTO user_roles(user_id,role_id)VALUES(:user,:role)')->execute(['user'=>$viewer,'role'=>$viewerRole]);$connection->prepare("INSERT INTO role_permissions(role_id,permission_id) SELECT :role,id FROM permissions WHERE slug IN ('admin.access','forms.view')")->execute(['role'=>$viewerRole]);$assert($app->auth()->attempt('forms-viewer@example.test','viewer-password'),'Viewer authentication failed.');$viewerList=$app->router()->dispatch(new Request('GET',$path));$assert($status($viewerList)===200&&!str_contains($content($viewerList),'View submissions'),'Submission-workspace link was exposed without forms.submissions.view.');$app->auth()->logout();$assert($app->auth()->attempt('forms-denied@example.test','denied-password'),'Denied user authentication failed.');foreach([$path,$path.'/'.$id.'/edit',$path.'/'.$id.'/publish',$path.'/'.$id.'/disable',$path.'/'.$id.'/delete'] as $protected){$method=str_contains($protected,'/edit')?'GET':'POST';$response=$app->router()->dispatch(new Request($method,$protected,[],['_token'=>'bad']));$assert($status($response)===403,'Authorization did not precede CSRF for '.$protected);}
 echo "M3.11 WU2 form Admin workspace passed ({$assertions} assertions).\n";
}finally{$server->exec('DROP DATABASE IF EXISTS '.$quoted);}
