<?php

declare(strict_types=1);

use Copot\Core\Config;
use Copot\Core\Database;
use Copot\Core\Env;
use Copot\Core\InstallerSchemaRunner;

$basePath = dirname(__DIR__); chdir($basePath); require $basePath . '/bootstrap/autoload.php'; Env::load($basePath . '/.env');
foreach (['FormIds.php', 'FormRecords.php', 'FormDefinitionValidator.php', 'SubmissionValueValidator.php', 'FormRepositories.php', 'FormServices.php'] as $file) require_once $basePath . '/modules/form-manager/Services/' . $file;
$assertions=0; $assert=static function(bool $condition,string $message)use(&$assertions):void{$assertions++;if(!$condition)throw new RuntimeException($message);};
$reject=static function(callable $operation,string $message)use($assert):void{try{$operation();$assert(false,$message);}catch(Throwable){$assert(true,$message);}};
$host=(string)Env::get('DB_HOST','127.0.0.1');$port=(int)Env::get('DB_PORT','3306');$username=(string)Env::get('DB_USERNAME','root');$password=(string)Env::get('DB_PASSWORD','');$name='copot_m311_domain_'.bin2hex(random_bytes(6));$quoted='`'.$name.'`';
$server=new PDO("mysql:host={$host};port={$port};charset=utf8mb4",$username,$password,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$server->exec('CREATE DATABASE '.$quoted.' CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
try {
    (new InstallerSchemaRunner($basePath.'/database/schema.sql'))->install(['host'=>$host,'port'=>$port,'database'=>$name,'username'=>$username,'password'=>$password]);
    $config=new Config($basePath.'/config');$reflection=new ReflectionClass($config);$items=$reflection->getProperty('items');$items->setAccessible(true);$configured=$items->getValue($config);foreach(['host'=>$host,'port'=>$port,'database'=>$name,'username'=>$username,'password'=>$password] as $key=>$value)$configured['database']['connections']['mysql'][$key]=$value;$items->setValue($config,$configured);$database=new Database($config);$connection=$database->connection();
    $forms=new FormRepository($database);$fields=new FormFieldRepository($database);$submissions=new FormSubmissionRepository($database);$definition=new FormDefinitionService($database,$forms,$fields,new FormDefinitionValidator());$lifecycle=new FormSubmissionLifecycleService($database,$forms,$fields,$submissions,new SubmissionValueValidator());
    foreach([0,-1,'1',1.0,true,[],new stdClass()] as $bad)$reject(fn()=>new FormId($bad),'FormId rejected invalid identifier.');$assert((new FormId(1))->value()===1,'FormId accepts a positive integer.');
    $validator=new FormDefinitionValidator();foreach(['draft','published','disabled'] as $state)$assert($validator->state($state)===$state,'Form state allowlist accepts '.$state);foreach(['text','email','textarea','select','checkbox'] as $type)$assert(in_array($type,FormDefinitionValidator::FIELD_TYPES,true),'Field type allowlist accepts '.$type);$reject(fn()=>$validator->state('archived'),'Unknown form state is rejected.');$reject(fn()=>new FormSubmission(new FormSubmissionId(1),new FormId(1),'archived',[],'now','now'),'Unknown submission state is rejected.');
    $field=static fn(string $key,string $type,int $order,array $extra=[]):array=>array_merge(['field_key'=>$key,'label'=>ucfirst($key),'field_type'=>$type,'sort_order'=>$order,'is_required'=>false,'min_length'=>null,'max_length'=>null,'options'=>[]],$extra);
    $select=$field('topic','select',1,['is_required'=>true,'options'=>[['option_value'=>'support','option_label'=>'Support','sort_order'=>1],['option_value'=>'sales','option_label'=>'Sales','sort_order'=>0]]]);
    $form=$definition->create(['name'=>' Contact form ','status'=>'published','fields'=>[$field('message','textarea',2,['is_required'=>true,'min_length'=>2,'max_length'=>100]),$select,$field('email','email',0,['is_required'=>true,'max_length'=>190]),$field('agree','checkbox',3,['is_required'=>true])]]);
    $assert($form->name()==='Contact form'&&$form->status()==='published','Form create normalizes name and stores state.');$ordered=$fields->forForm($form->id());$assert(array_map(fn(FormField $item)=>$item->key(),$ordered)===['email','topic','message','agree'],'Fields use deterministic sort order.');$assert(array_map(fn(FormFieldOption $item)=>$item->value(),$ordered[1]->options())===['sales','support'],'Options use deterministic sort order.');
    $reject(fn()=>$definition->create(['name'=>'', 'status'=>'draft','fields'=>[]]),'Empty form name is rejected.');$reject(fn()=>$definition->create(['name'=>str_repeat('x',151),'status'=>'draft','fields'=>[]]),'Overlong form name is rejected.');$reject(fn()=>$definition->create(['name'=>"bad\nname",'status'=>'draft','fields'=>[]]),'Control characters in form name are rejected.');$reject(fn()=>$definition->create(['name'=>'Bad','status'=>'draft','fields'=>[$field('bad key','text',0)]]),'Malformed field key is rejected.');$reject(fn()=>$definition->create(['name'=>'Bad','status'=>'draft','fields'=>[$field('a','unknown',0)]]),'Unknown field type is rejected.');$reject(fn()=>$definition->create(['name'=>'Bad','status'=>'draft','fields'=>[$field('a','text',0),$field('a','text',1)]]),'Duplicate field key is rejected.');$reject(fn()=>$definition->create(['name'=>'Bad','status'=>'draft','fields'=>[$field('a','text',0),$field('b','text',0)]]),'Duplicate field order is rejected.');
    $reject(fn()=>$definition->create(['name'=>'Bad','status'=>'draft','fields'=>[
        $field('a','text',0,['options'=>[
            ['option_value'=>'x','option_label'=>'X','sort_order'=>0],
        ]]),
    ]]),'Options for non-select field are rejected.');
    $reject(fn()=>$definition->create(['name'=>'Bad','status'=>'draft','fields'=>[$field('a','select',0)]]),'Select without options is rejected.');$reject(fn()=>$definition->create(['name'=>'Bad','status'=>'draft','fields'=>[$field('a','text',0,['min_length'=>4,'max_length'=>2])]]),'Inconsistent length constraints are rejected.');
    $submission=$lifecycle->persist($form->id(),['email'=>' TEST@EXAMPLE.TEST ','topic'=>'support','message'=>'Hello','agree'=>'1']);$assert($submission->status()==='new'&&count($submission->values())===4,'Submission starts new with all normalized values.');$values=[];foreach($submission->values() as $value)$values[$value->fieldKey()]=$value;$assert($values['email']->valueText()==='test@example.test'&&$values['topic']->valueLabel()==='Support'&&$values['agree']->valueText()==='1','Email, select snapshot, and checkbox normalization passed.');
    $reject(fn()=>$lifecycle->persist($form->id(),['email'=>'bad','topic'=>'support','message'=>'Hello','agree'=>'1']),'Invalid email is rejected.');$reject(fn()=>$lifecycle->persist($form->id(),['email'=>'x@example.test','topic'=>'bad','message'=>'Hello','agree'=>'1']),'Unknown select option is rejected.');$reject(fn()=>$lifecycle->persist($form->id(),['email'=>'x@example.test','topic'=>'sales','message'=>'x','agree'=>'1']),'Minimum length is enforced.');$reject(fn()=>$lifecycle->persist($form->id(),['email'=>'x@example.test','topic'=>'sales','message'=>'Hello','agree'=>'0']),'Required checkbox is enforced.');$reject(fn()=>$lifecycle->persist($form->id(),['email'=>'x@example.test','topic'=>'sales','message'=>'Hello','agree'=>'1','unknown'=>'x']),'Unknown submission key is rejected.');
    $reviewed=$lifecycle->markReviewed($submission->id());$assert($reviewed->status()==='reviewed','Review lifecycle transition succeeds.');$oldLabel=$values['topic']->fieldLabel();$definition->update($form->id(),['name'=>'Contact form','status'=>'published','fields'=>[$field('message','textarea',2,['is_required'=>true,'min_length'=>2,'max_length'=>100]),$field('topic','select',1,['is_required'=>true,'label'=>'New topic label','options'=>[['option_value'=>'support','option_label'=>'New support','sort_order'=>0]]]),$field('email','email',0,['is_required'=>true,'max_length'=>190]),$field('agree','checkbox',3,['is_required'=>true])]],$form->updatedAt());$historic=$submissions->findById($submission->id());$historicValues=[];foreach($historic->values() as $value)$historicValues[$value->fieldKey()]=$value;$assert($historicValues['topic']->fieldLabel()===$oldLabel&&$historicValues['topic']->valueLabel()==='Support','Definition edit does not rewrite snapshots.');
    $freshForm=$forms->findById($form->id());$definition->update($form->id(),['name'=>'Contact form','status'=>'published','fields'=>[$field('message','textarea',2,['is_required'=>true,'min_length'=>2,'max_length'=>100]),$field('email','email',0,['is_required'=>true,'max_length'=>190]),$field('agree','checkbox',3,['is_required'=>true])]],$freshForm->updatedAt());$historic=$submissions->findById($submission->id());foreach($historic->values() as $value)if($value->fieldKey()==='topic')$assert($value->fieldId()===null&&$value->fieldLabel()===$oldLabel,'Removed field preserves nullable provenance and snapshots.');
    $reject(fn()=>$definition->delete($form->id()),'Form deletion is rejected while submissions exist.');$definition->disable($form->id());$assert($forms->findById($form->id())?->status()==='disabled','Disabled form remains retained.');$reject(fn()=>$lifecycle->persist($form->id(),['email'=>'x@example.test','message'=>'Hi','agree'=>'1']),'Disabled form accepts no submission.');
    $connection->beginTransaction();$draft=$definition->create(['name'=>'Nested','status'=>'draft','fields'=>[]]);$assert($connection->inTransaction(),'Nested success retains caller transaction.');try{$definition->create(['name'=>'Bad','status'=>'draft','fields'=>[$field('a','text',0),$field('b','text',0)]]);}catch(InvalidArgumentException){}$assert($connection->inTransaction(),'Nested validation failure retains caller transaction.');$connection->rollBack();$assert($forms->findById($draft->id())===null,'Caller rollback removes nested write.');
    $lifecycle->delete($submission->id());$assert($submissions->findById($submission->id())===null&&(int)$connection->query('SELECT COUNT(*) FROM form_submission_values')->fetchColumn()===0,'Hard deletion cascades submission values.');
    echo "M3.11 WU1 form domain passed ({$assertions} assertions).\n";
} finally {$server->exec('DROP DATABASE IF EXISTS '.$quoted);}
