<?php

declare(strict_types=1);

use Copot\Core\Application;
use Copot\Core\Config;
use Copot\Core\Database;
use Copot\Core\Env;
use Copot\Core\InstallerSchemaRunner;
use Copot\Core\Request;
use Copot\Core\Response;

$base = dirname(__DIR__); chdir($base); session_save_path(sys_get_temp_dir()); session_id('copotm311wu4'.bin2hex(random_bytes(5))); require $base.'/bootstrap/autoload.php'; Env::load($base.'/.env');
$assertions=0; $assert=static function(bool $ok,string $message)use(&$assertions):void{$assertions++;if(!$ok)throw new RuntimeException($message);}; $read=static fn(Response $r,string $p):mixed=>(new ReflectionProperty(Response::class,$p))->getValue($r); $status=static fn(Response $r):int=>(int)$read($r,'status'); $location=static fn(Response $r):?string=>$read($r,'headers')['Location']??null; $body=static fn(Response $r):string=>(string)$read($r,'content');
$host=(string)Env::get('DB_HOST','127.0.0.1');$port=(int)Env::get('DB_PORT',3306);$username=(string)Env::get('DB_USERNAME','root');$password=(string)Env::get('DB_PASSWORD','');$name='copot_m311_wu4_'.bin2hex(random_bytes(6));$quoted='`'.$name.'`';$server=new PDO("mysql:host={$host};port={$port};charset=utf8mb4",$username,$password,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$server->exec('CREATE DATABASE '.$quoted.' CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
try {
 (new InstallerSchemaRunner($base.'/database/schema.sql'))->install(['host'=>$host,'port'=>$port,'database'=>$name,'username'=>$username,'password'=>$password]); $_ENV['DB_DATABASE']=$name; putenv('DB_DATABASE='.$name); $db=(new Database(new Config($base.'/config')))->connection(); $db->exec("INSERT INTO themes(theme_id,name,version,type,path,is_active,metadata,created_at,updated_at)VALUES('default','Default','0.1.0','frontend','themes/default',1,'{\"entry\":{\"layout\":\"layouts/app.php\"}}',NOW(),NOW())"); $db->exec("INSERT INTO modules(name,title,version,path,status,installed_at,created_at,updated_at)VALUES('form-manager','Form Manager','0.1.0','modules/form-manager','enabled',NOW(),NOW(),NOW())");
 $db->exec("INSERT INTO forms(name,status,created_at,updated_at)VALUES('Public <Form>','published',NOW(),NOW())");$form=(int)$db->lastInsertId();$db->exec("INSERT INTO forms(name,status,created_at,updated_at)VALUES('Draft form','draft',NOW(),NOW())");$draft=(int)$db->lastInsertId();$fields=[['text','Text <label>',0,1],['email','Email',1,0],['textarea','Message',2,0],['select','Choice',3,0],['checkbox','Agree',4,0]];foreach($fields as[$type,$label,$order,$required]){$max=in_array($type,['select','checkbox'],true)?null:4000;$s=$db->prepare('INSERT INTO form_fields(form_id,field_key,label,field_type,sort_order,is_required,min_length,max_length,created_at,updated_at)VALUES(:form,:key,:label,:type,:order,:required,NULL,:max,NOW(),NOW())');$s->execute(['form'=>$form,'key'=>$type,'label'=>$label,'type'=>$type,'order'=>$order,'required'=>$required,'max'=>$max]);$fieldId=(int)$db->lastInsertId();if($type==='select')$db->exec("INSERT INTO form_field_options(form_field_id,option_value,option_label,sort_order,created_at,updated_at)VALUES({$fieldId},'one','One <option>',0,NOW(),NOW()),({$fieldId},'two','Two',1,NOW(),NOW())");}
 $app=new Application($base);$app->session()->start();require $base.'/routes/web.php';require $base.'/routes/auth.php';require $base.'/routes/admin.php';$app->moduleLoader()->loadResolvers($app);$app->moduleLoader()->loadRoutes($app);require $base.'/routes/admin_fallback.php';$_SERVER['REMOTE_ADDR']='127.0.0.1';unset($_SERVER['CONTENT_LENGTH']);
	 $path='/forms/'.$form;$get=$app->router()->dispatch(new Request('GET',$path));$html=$body($get);$assert($status($get)===200&&str_contains($html,'Public &lt;Form&gt;')&&str_contains($html,'type="email"')&&str_contains($html,'<textarea')&&str_contains($html,'<select')&&str_contains($html,'type="checkbox"')&&str_contains($html,'One &lt;option&gt;'),'Published public form did not render the bounded field vocabulary.');$assert(str_contains($html,'aria-hidden="true"')&&str_contains($html,'autocomplete="off"'),'Honeypot was not hidden accessibly.');$token=$app->csrf()->token();$nonces=$app->session()->get('_copot_form_render_nonces');$nonce=(string)array_key_first($nonces);$nonces[$nonce]['issued_at']=time()-4;$app->session()->set('_copot_form_render_nonces',$nonces);
 $values=['text'=>'Hello','email'=>'USER@example.test','textarea'=>'Line 1\r\nLine 2','select'=>'one','checkbox'=>'1'];$post=$app->router()->dispatch(new Request('POST',$path,[],['_token'=>$token,'_form_nonce'=>$nonce,'_form_website'=>'','values'=>$values]));$assert($status($post)===302&&$location($post)===$path.'?submitted=1','Valid submission did not use success PRG.');$assert((int)$db->query('SELECT COUNT(*) FROM form_submissions')->fetchColumn()===1&&(string)$db->query('SELECT value_text FROM form_submission_values WHERE field_key="email"')->fetchColumn()==='user@example.test','Submission snapshots were not persisted and normalized.');$replay=$app->router()->dispatch(new Request('POST',$path,[],['_token'=>$token,'_form_nonce'=>$nonce,'_form_website'=>'','values'=>$values]));$assert($status($replay)===422&&((int)$db->query('SELECT COUNT(*) FROM form_submissions')->fetchColumn()===1),'Consumed nonce replay was accepted.');
 $under=$app->router()->dispatch(new Request('GET',$path));$underNonce=(string)array_key_first($app->session()->get('_copot_form_render_nonces'));$tooSoon=$app->router()->dispatch(new Request('POST',$path,[],['_token'=>$token,'_form_nonce'=>$underNonce,'_form_website'=>'','values'=>$values]));$assert($status($tooSoon)===422,'Minimum submission duration was not enforced.');$missingCsrf=$app->router()->dispatch(new Request('POST',$path,[],['_form_nonce'=>$underNonce,'_form_website'=>'','values'=>$values]));$assert($status($missingCsrf)===419,'Missing CSRF token did not return 419.');$honeypot=$app->router()->dispatch(new Request('POST',$path,[],['_token'=>$token,'_form_nonce'=>$underNonce,'_form_website'=>'filled','values'=>$values]));$assert($status($honeypot)===422,'Populated honeypot was accepted.');
	 $_SERVER['REMOTE_ADDR']='127.0.0.9';$invalid=$app->router()->dispatch(new Request('POST',$path,[],['_token'=>$token,'_form_nonce'=>$underNonce,'_form_website'=>'','values'=>['text'=>['bad']]]));$assert($status($invalid)===422&&!str_contains($body($invalid),'SQL'),'Malformed field arrays did not fail safely.');$oversized=$_SERVER['CONTENT_LENGTH']='262145';$large=$app->router()->dispatch(new Request('POST',$path,[],['_token'=>$token,'_form_nonce'=>$underNonce,'_form_website'=>'','values'=>$values]));unset($_SERVER['CONTENT_LENGTH']);$assert($status($large)===422,'Oversized body was not rejected.');$draftResponse=$app->router()->dispatch(new Request('GET','/forms/'.$draft));$assert($status($draftResponse)===404,'Draft form was publicly rendered.');$malformed=$app->router()->dispatch(new Request('GET','/forms/0'));$assert($status($malformed)===404,'Malformed public form ID did not return 404.');
	 $_SERVER['REMOTE_ADDR']='127.0.0.1';for($i=0;$i<4;$i++){ $r=$app->router()->dispatch(new Request('GET',$path));$n=(string)array_key_last($app->session()->get('_copot_form_render_nonces'));$map=$app->session()->get('_copot_form_render_nonces');$map[$n]['issued_at']=time()-4;$app->session()->set('_copot_form_render_nonces',$map);$r=$app->router()->dispatch(new Request('POST',$path,[],['_token'=>$token,'_form_nonce'=>$n,'_form_website'=>'','values'=>$values]));$assert($status($r)===302,'Rate-limit fixture attempt did not persist.');}
 $r=$app->router()->dispatch(new Request('GET',$path));$n=(string)array_key_last($app->session()->get('_copot_form_render_nonces'));$map=$app->session()->get('_copot_form_render_nonces');$map[$n]['issued_at']=time()-4;$app->session()->set('_copot_form_render_nonces',$map);$blocked=$app->router()->dispatch(new Request('POST',$path,[],['_token'=>$token,'_form_nonce'=>$n,'_form_website'=>'','values'=>$values]));$assert($status($blocked)===429,'Sixth attempt was not rate limited.');$_SERVER['REMOTE_ADDR']='127.0.0.2';$r=$app->router()->dispatch(new Request('GET',$path));$n=(string)array_key_last($app->session()->get('_copot_form_render_nonces'));$map=$app->session()->get('_copot_form_render_nonces');$map[$n]['issued_at']=time()-4;$app->session()->set('_copot_form_render_nonces',$map);$otherClient=$app->router()->dispatch(new Request('POST',$path,[],['_token'=>$token,'_form_nonce'=>$n,'_form_website'=>'','values'=>$values]));$assert($status($otherClient)===302,'Rate limit was not isolated per client.');
 $db->exec("UPDATE form_fields SET field_type='unknown' WHERE form_id={$form} AND field_key='text'");$corrupt=$app->router()->dispatch(new Request('GET',$path));$assert($status($corrupt)===503&&str_contains($body($corrupt),'temporarily unavailable'),'Corrupt definition did not fail closed.');
 echo "M3.11 WU4 public submission passed ({$assertions} assertions).\n";
} finally { $server->exec('DROP DATABASE IF EXISTS '.$quoted); }
