<?php

declare(strict_types=1);

use Copot\Core\Env;
use Copot\Core\InstallerSchemaRunner;
use Copot\Core\ThemeDiscovery;
use Copot\Core\ThemeSettingsService;
use Copot\Core\ThemeSettingsStorage;

$basePath = dirname(__DIR__);
chdir($basePath);
require $basePath . '/bootstrap/autoload.php';
Env::load($basePath . '/.env');
$assertions = 0;
$assert = static function (bool $condition, string $message) use (&$assertions): void { $assertions++; if (!$condition) throw new RuntimeException($message); };
$host = (string) Env::get('DB_HOST', '127.0.0.1'); $port = (int) Env::get('DB_PORT', '3306'); $username = (string) Env::get('DB_USERNAME', 'root'); $password = (string) Env::get('DB_PASSWORD', '');
$databaseName = 'copot_m37_wu5_' . bin2hex(random_bytes(5)); $configuration = compact('host', 'port', 'username', 'password') + ['database' => $databaseName];
$server = new PDO("mysql:host={$host};port={$port};charset=utf8mb4", $username, $password, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
$server->exec('CREATE DATABASE `' . $databaseName . '` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
$fixtureRoot = $basePath . DIRECTORY_SEPARATOR . 'storage' . DIRECTORY_SEPARATOR . '.m37-wu5-' . bin2hex(random_bytes(4)); mkdir($fixtureRoot, 0777, true);
$cleanup = static function () use ($server, $databaseName, $fixtureRoot): void { if (is_dir($fixtureRoot)) { $it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($fixtureRoot, FilesystemIterator::SKIP_DOTS), RecursiveIteratorIterator::CHILD_FIRST); foreach ($it as $file) $file->isDir() ? rmdir($file->getPathname()) : unlink($file->getPathname()); rmdir($fixtureRoot); } $server->exec('DROP DATABASE IF EXISTS `' . $databaseName . '`'); };
try {
    (new InstallerSchemaRunner($basePath . '/database/schema.sql'))->install($configuration); $_ENV['DB_DATABASE'] = $databaseName; putenv('DB_DATABASE=' . $databaseName);
    $make = static function (string $id, string $name) use ($fixtureRoot): void { $path = $fixtureRoot . DIRECTORY_SEPARATOR . $id; mkdir($path . DIRECTORY_SEPARATOR . 'layouts', 0777, true); file_put_contents($path . '/layouts/app.php', '<?php echo "L" . ($themeSettings["accent"] ?? "default") . ($content ?? "");'); file_put_contents($path . '/content.php', '<?php echo "C" . ($themeSettings["accent"] ?? "default");'); file_put_contents($path . '/theme.json', json_encode(['id'=>$id,'name'=>$name,'version'=>'1.0.0','type'=>'frontend','entry'=>['layout'=>'layouts/app.php'],'supports'=>['navigation_locations'=>['primary','footer']],'settings'=>['version'=>1,'sections'=>[['id'=>'appearance','label'=>'Appearance','fields'=>[['key'=>'accent','label'=>'Accent','type'=>'string','control'=>'color','default'=>'#ffffff','validation'=>['format'=>'hex_color']],['key'=>'enabled','label'=>'Enabled','type'=>'boolean','control'=>'checkbox','default'=>false,'validation'=>[]],['key'=>'count','label'=>'Count','type'=>'integer','control'=>'number','default'=>2,'validation'=>['min'=>0,'max'=>10]],['key'=>'ratio','label'=>'Ratio','type'=>'float','control'=>'number','default'=>1.5,'validation'=>['min'=>0.0,'max'=>3.0]],['key'=>'mode','label'=>'Mode','type'=>'string','control'=>'select','default'=>'light','validation'=>['allowed_values'=>['light','dark']]],['key'=>'title','label'=>'Title','type'=>'string','control'=>'text','default'=>'Default','validation'=>['max_length'=>40]]]]]]], JSON_THROW_ON_ERROR)); };
    $make('inactive-theme-with-a-very-long-identifier-that-must-map-safely', 'Inactive'); $make('active', 'Active');
    $discovery = new ThemeDiscovery($fixtureRoot); $definitions = $discovery->discover(); $inactive = $definitions[0]->id() === 'active' ? $definitions[1] : $definitions[0]; $active = $definitions[0]->id() === 'active' ? $definitions[0] : $definitions[1];
    $assert(strlen(ThemeSettingsStorage::namespaceFor($inactive->id())) <= 64, 'Long Theme ID produced an oversized namespace.'); $assert(ThemeSettingsStorage::namespaceFor($inactive->id()) !== ThemeSettingsStorage::namespaceFor($active->id()), 'Theme namespace mapper collided.');
    $database = new Copot\Core\Database(new Copot\Core\Config($basePath . '/config')); $db = $database->connection(); $service = new ThemeSettingsService(new Copot\Core\SettingsRepository($database), $database);
    $assert($service->values($inactive) === ['accent'=>'#ffffff','count'=>2,'enabled'=>false,'mode'=>'light','ratio'=>1.5,'title'=>'Default'], 'Declared defaults did not resolve deterministically.');
    $fields = $service->fields($inactive); $controls = array_column($fields[0]['fields'], 'control'); sort($controls); $assert(count($fields) === 1 && count($fields[0]['fields']) === 6, 'All six locked controls were not represented.'); $assert($controls === ['checkbox','color','number','number','select','text'], 'Control vocabulary was not preserved.');
    $service->save($inactive, ['accent'=>'#112233','enabled'=>'1','count'=>'4','ratio'=>'2.5','mode'=>'dark','title'=>'Saved']); $assert($service->values($inactive) === ['accent'=>'#112233','count'=>4,'enabled'=>true,'mode'=>'dark','ratio'=>2.5,'title'=>'Saved'], 'Inactive Theme settings did not persist with strict types.'); $service->save($inactive, ['accent'=>'#112233','enabled'=>'1','count'=>'4','ratio'=>'2.5','mode'=>'dark','title'=>'Saved']); $assert($service->values($inactive)['count'] === 4, 'Repeated save was not idempotent.');
    try { $service->save($inactive, ['accent'=>'#bad','enabled'=>['1'],'count'=>'4','ratio'=>'2.5','mode'=>'unknown','title'=>'x']); $assert(false, 'Invalid settings unexpectedly saved.'); } catch (Copot\Core\ThemeSettingsValidationException $failure) { $assert($failure->fieldErrors() !== [] && array_key_exists('mode', $failure->submitted()) && $failure->submitted()['mode'] === 'unknown', 'Validation errors or submitted values were not retained.'); } $assert($service->values($inactive)['mode'] === 'dark', 'Validation failure changed stored values.');
    $service->reset($inactive); $assert($service->values($inactive) === ['accent'=>'#ffffff','count'=>2,'enabled'=>false,'mode'=>'light','ratio'=>1.5,'title'=>'Default'], 'Theme reset did not restore defaults.'); $service->reset($inactive); $assert($service->values($inactive)['title'] === 'Default', 'Repeated reset was not idempotent.');
    $namespace = ThemeSettingsStorage::namespaceFor($inactive->id()); $db->prepare('INSERT INTO settings (namespace,setting_key,setting_value,value_type,created_at,updated_at) VALUES (?,?,?,?,NOW(),NOW())')->execute([$namespace,'obsolete','old','string']); $service->reset($inactive); $assert((int) $db->query("SELECT COUNT(*) FROM settings WHERE namespace = '{$namespace}'")->fetchColumn() === 0, 'Reset did not remove obsolete Theme-owned overrides.');
    $db->prepare('INSERT INTO settings (namespace,setting_key,setting_value,value_type,created_at,updated_at) VALUES (?,?,?,?,NOW(),NOW())')->execute([$namespace,'accent','not-a-color','string']); $assert($service->values($inactive)['accent'] === '#ffffff', 'Corrupt override did not fail closed to default.');
    $saveTrigger = 'wu5_save_fail_' . bin2hex(random_bytes(4)); $db->exec("CREATE TRIGGER {$saveTrigger} BEFORE INSERT ON settings FOR EACH ROW BEGIN IF NEW.setting_key = 'ratio' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'controlled'; END IF; END"); try { $service->save($inactive, ['accent'=>'#101010','enabled'=>'1','count'=>'3','ratio'=>'2.0','mode'=>'dark','title'=>'Should rollback']); $assert(false, 'Triggered save failure unexpectedly succeeded.'); } catch (Throwable) { $assert($service->values($inactive)['title'] === 'Default' && $service->values($inactive)['enabled'] === false, 'Save trigger failure did not roll back earlier field writes.'); } $db->exec("DROP TRIGGER {$saveTrigger}");
    $otherNamespace = ThemeSettingsStorage::namespaceFor($active->id()); $db->prepare('INSERT INTO settings (namespace,setting_key,setting_value,value_type,created_at,updated_at) VALUES (?,?,?,?,NOW(),NOW())')->execute([$otherNamespace,'accent','#abcdef','string']); $deleteTrigger = 'wu5_delete_fail_' . bin2hex(random_bytes(4)); $db->exec("CREATE TRIGGER {$deleteTrigger} BEFORE DELETE ON settings FOR EACH ROW BEGIN IF OLD.namespace = '{$namespace}' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'controlled'; END IF; END"); try { $service->reset($inactive); $assert(false, 'Triggered reset failure unexpectedly succeeded.'); } catch (Throwable) { $assert((int) $db->query("SELECT COUNT(*) FROM settings WHERE namespace = '{$namespace}'")->fetchColumn() === 1 && (int) $db->query("SELECT COUNT(*) FROM settings WHERE namespace = '{$otherNamespace}'")->fetchColumn() === 1, 'Reset trigger failure did not preserve prior or other Theme overrides.'); } $db->exec("DROP TRIGGER {$deleteTrigger}");
    $db->exec("UPDATE themes SET is_active = 0 WHERE type = 'frontend'"); $db->prepare('INSERT INTO themes (theme_id,name,version,type,path,is_active,metadata,created_at,updated_at) VALUES (?,?,?,?,?,1,?,NOW(),NOW())')->execute([$active->id(),$active->name(),$active->version(),$active->type(),'storage/' . basename($fixtureRoot) . '/' . $active->id(),json_encode($active->metadata(), JSON_THROW_ON_ERROR)]);
    $resolver = new Copot\Core\ThemeSettingsResolver(new Copot\Core\ThemeRepository(new Copot\Core\Database(new Copot\Core\Config($basePath . '/config'))), $service);
    $assert($resolver->resolve() === ['accent'=>'#abcdef','count'=>2,'enabled'=>false,'mode'=>'light','ratio'=>1.5,'title'=>'Default'], 'Runtime resolver did not expose only active Theme values.');
    $db->prepare('UPDATE settings SET setting_value = ? WHERE namespace = ? AND setting_key = ?')->execute(['#abcdef', ThemeSettingsStorage::namespaceFor($inactive->id()), 'accent']);
    $assert($resolver->resolve() === ['accent'=>'#abcdef','count'=>2,'enabled'=>false,'mode'=>'light','ratio'=>1.5,'title'=>'Default'], 'Inactive Theme settings leaked into active runtime output.');
    $db->exec("UPDATE themes SET metadata = '{\"settings\":{\"version\":1,\"sections\":[{\"id\":\"bad\",\"label\":\"Bad\",\"fields\":[{\"key\":\"ok\",\"label\":\"OK\",\"type\":\"string\",\"control\":\"text\",\"default\":\"x\",\"validation\":[]},{\"key\":\"broken\",\"label\":[]}] } ]}}' WHERE theme_id = 'active'"); $assert($resolver->resolve() === [], 'Malformed active metadata was partially exposed.');
    $db->exec("UPDATE themes SET metadata = " . $db->quote(json_encode($active->metadata(), JSON_THROW_ON_ERROR)) . " WHERE theme_id = 'active'");
    $application = new Copot\Core\Application($basePath); $rendered = $application->viewRenderer()->renderFile($fixtureRoot . '/active/content.php'); $assert($rendered === 'L#abcdefC#abcdef', 'Intrinsic themeSettings was not available: ' . $rendered);
    $db->beginTransaction(); $db->exec("INSERT INTO settings (namespace,setting_key,setting_value,value_type,created_at,updated_at) VALUES ('caller_marker','value','kept','string',NOW(),NOW())"); $service->save($inactive, ['accent'=>'#123456','enabled'=>'0','count'=>'3','ratio'=>'1.5','mode'=>'light','title'=>'Nested']); $assert($db->inTransaction() && $service->values($inactive)['title'] === 'Nested', 'Nested save closed the caller transaction.'); $db->rollBack(); $assert($service->values($inactive)['title'] === 'Default', 'Caller rollback did not remove nested Theme settings.');
    $nestedTrigger = 'wu5_nested_fail_' . bin2hex(random_bytes(4)); $db->exec("CREATE TRIGGER {$nestedTrigger} BEFORE INSERT ON settings FOR EACH ROW BEGIN IF NEW.setting_key = 'ratio' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'controlled'; END IF; END"); $db->beginTransaction(); $db->exec("INSERT INTO settings (namespace,setting_key,setting_value,value_type,created_at,updated_at) VALUES ('caller_marker','value','kept','string',NOW(),NOW()) ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)"); try { $service->save($inactive, ['accent'=>'#222222','enabled'=>'1','count'=>'5','ratio'=>'2.0','mode'=>'dark','title'=>'Nested failure']); $assert(false, 'Nested triggered save unexpectedly succeeded.'); } catch (Throwable) { $assert($db->inTransaction() && (int) $db->query("SELECT COUNT(*) FROM settings WHERE namespace = 'caller_marker'")->fetchColumn() === 1 && $service->values($inactive)['title'] === 'Default', 'Nested failure did not preserve caller work and previous overrides.'); } $db->rollBack(); $db->exec("DROP TRIGGER {$nestedTrigger}");
    echo "M3.7 Work Unit 5 Theme settings passed ({$assertions} assertions).\n";
} finally { $cleanup(); }
