<?php

declare(strict_types=1);

use Copot\Core\Config;
use Copot\Core\Database;
use Copot\Core\Env;
use Copot\Core\InstallerSchemaRunner;

$base = dirname(__DIR__);
chdir($base);
require $base . '/bootstrap/autoload.php';
Env::load($base . '/.env');
foreach (['MediaId','Media','MediaVariant','MediaUsage','MediaRepository','MediaVariantRepository','MediaUsageRepository','MediaFileInspector','MediaStagedFile','MediaProcessingException','MediaProcessingFacts','MediaProcessingRequest','MediaImageProcessor','MediaGdImageProcessor','MediaFilesystemStorage','MediaVariantFilesystemStorage','MediaLifecycleService','MediaContentReferenceService'] as $file) require_once $base . '/modules/media/Services/' . $file . '.php';
foreach (['Content','ContentRepository','ContentService'] as $file) require_once $base . '/modules/content/Services/' . $file . '.php';

$assertions = 0;
$assert = static function (bool $condition, string $message) use (&$assertions): void { $assertions++; if (!$condition) throw new RuntimeException($message); };
$host = (string) Env::get('DB_HOST', '127.0.0.1'); $port = (int) Env::get('DB_PORT', '3306'); $username = (string) Env::get('DB_USERNAME', 'root'); $password = (string) Env::get('DB_PASSWORD', '');
$name = 'copot_m38_wu6_' . bin2hex(random_bytes(6)); $quoted = '`' . str_replace('`', '``', $name) . '`';
$server = new PDO("mysql:host={$host};port={$port};charset=utf8mb4", $username, $password, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
$server->exec('CREATE DATABASE ' . $quoted . ' CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
$config = ['host'=>$host,'port'=>$port,'database'=>$name,'username'=>$username,'password'=>$password];

try {
    (new InstallerSchemaRunner($base . '/database/schema.sql'))->install($config);
    $pdo = new PDO("mysql:host={$host};port={$port};dbname={$name};charset=utf8mb4", $username, $password, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC]);
    $upgrade = (string) file_get_contents($base . '/database/upgrades/m3_8_media_library.sql');
    foreach (array_filter(array_map('trim', preg_split('/;\s*(?:\R|$)/', $upgrade) ?: [])) as $statement) $pdo->exec($statement);
    foreach (array_filter(array_map('trim', preg_split('/;\s*(?:\R|$)/', $upgrade) ?: [])) as $statement) $pdo->exec($statement);
    $assert((bool) $pdo->query("SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'content' AND column_name = 'featured_media_id'")->fetchColumn(), 'featured_media_id upgrade is not idempotent.');

    $cfg = new Config($base . '/config'); $reflection = new ReflectionClass($cfg); $property = $reflection->getProperty('items'); $property->setAccessible(true); $items = $property->getValue($cfg); foreach ($config as $key => $value) $items['database']['connections']['mysql'][$key] = $value; $property->setValue($cfg, $items);
    $database = new Database($cfg); $media = new MediaRepository($database); $variants = new MediaVariantRepository($database); $usages = new MediaUsageRepository($database); $original = new MediaFilesystemStorage($base . '/storage/test-wu6-media'); $variant = new MediaVariantFilesystemStorage($base . '/storage/test-wu6-media');
    $lifecycle = new MediaLifecycleService($database, $media, $variants, $usages, $original, $variant); $references = new MediaContentReferenceService($database, $media, $usages); $contents = new ContentRepository($database); $service = new ContentService($database, $contents, null, $references);
    $makeMedia = static function (string $key, string $mime = 'image/png') use ($media): int { return $media->create(['kind'=>'image','original_filename'=>'featured.png','title'=>'Featured','storage_key'=>str_repeat($key,32).'.png','mime_type'=>$mime,'extension'=>'png','byte_size'=>4,'width'=>10,'height'=>10])->value(); };
    $allowed = $makeMedia('a'); $second = $makeMedia('c'); $pdf = $makeMedia('d', 'application/pdf');
    $payload = ['type'=>'page','title'=>'Featured page','slug'=>'featured-page','excerpt'=>null,'body'=>'Body','status'=>'draft','author_id'=>null,'featured_media_id'=>$allowed];
    $contentId = $service->create($payload); $row = $contents->findById($contentId); $assert($row?->featuredMediaId() === $allowed, 'Content create did not persist featured_media_id.'); $assert(count($usages->forConsumer('content', $contentId, 'featured_media')) === 1, 'Content create did not register usage.');
    $service->update($contentId, [...$payload, 'featured_media_id'=>$second], [], $row->updatedAt()); $row = $contents->findById($contentId); $assert($row?->featuredMediaId() === $second && $usages->forConsumer('content', $contentId, 'featured_media')[0]->mediaId()->value() === $second, 'Content replacement did not synchronize usage.');
    $service->update($contentId, [...$payload, 'featured_media_id'=>null], [], $row->updatedAt()); $assert($contents->findById($contentId)?->featuredMediaId() === null && $usages->forConsumer('content', $contentId, 'featured_media') === [], 'Content clear did not remove usage.');
    try { $service->create([...$payload, 'slug'=>'invalid-pdf','featured_media_id'=>$pdf]); $assert(false, 'Disallowed PDF reference was accepted.'); } catch (InvalidArgumentException) { $assert(true, 'Disallowed MIME was rejected.'); }
    $service->create([...$payload, 'slug'=>'rollback-page','featured_media_id'=>null]);
    try { $service->create([...$payload, 'slug'=>'missing-media','featured_media_id'=>999999999]); $assert(false, 'Missing Media reference was accepted.'); } catch (InvalidArgumentException) { $assert((int) $pdo->query("SELECT COUNT(*) FROM content WHERE slug = 'missing-media'")->fetchColumn() === 0, 'Failed Content create was not rolled back.'); }
    $service->delete($contentId); $assert($usages->forConsumer('content', $contentId, 'featured_media') === [], 'Deleting Content did not remove usage.');
    $lifecycle->registerUsage($allowed, 'content', 77, 'featured_media'); try { $lifecycle->delete($allowed); $assert(false, 'Used Media deletion was not blocked.'); } catch (MediaInUseException) { $assert(true, 'Used Media deletion was blocked.'); } $lifecycle->removeUsage($allowed, 'content', 77, 'featured_media');
    $storageRoot = $base . '/storage/test-wu6-media'; @mkdir($storageRoot . '/originals/cc/cc', 0755, true); @mkdir($storageRoot . '/variants/bb/bb', 0755, true); file_put_contents($storageRoot . '/originals/cc/cc/' . str_repeat('c',32) . '.png', 'orig');
    $variantKey = str_repeat('b',32) . '.png'; file_put_contents($storageRoot . '/variants/bb/bb/' . $variantKey, 'variant'); $variants->saveDescriptor(['media_id'=>$second,'variant_key'=>'featured','storage_key'=>$variantKey,'mime_type'=>'image/png','extension'=>'png','byte_size'=>7,'width'=>10,'height'=>10]);
    $trigger = 'wu6_delete_fail_' . bin2hex(random_bytes(4)); $pdo->exec("CREATE TRIGGER {$trigger} BEFORE DELETE ON media FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'controlled'"); try { $lifecycle->delete($second); $assert(false, 'Quarantine compensation delete unexpectedly succeeded.'); } catch (Throwable) { $assert($media->findById($second) !== null && is_file($storageRoot . '/originals/cc/cc/' . str_repeat('c',32) . '.png') && is_file($storageRoot . '/variants/bb/bb/' . $variantKey), 'Quarantine compensation did not restore files.'); } $pdo->exec("DROP TRIGGER {$trigger}");
    $lifecycle->delete($second); $assert($media->findById($second) === null, 'Unused Media was not deleted.');
    $rasterSource = tempnam(sys_get_temp_dir(), 'copot-wu6-source-'); $rasterOutput = tempnam(sys_get_temp_dir(), 'copot-wu6-output-');
    $raster = imagecreatetruecolor(160, 90); $black = imagecolorallocate($raster, 0, 0, 0); $green = imagecolorallocate($raster, 0, 220, 0); imagefill($raster, 0, 0, $black); imagefilledrectangle($raster, 40, 20, 119, 64, $green); imagepng($raster, $rasterSource); imagedestroy($raster);
    $rasterRequest = MediaProcessingRequest::fromArray($allowed, ['crop'=>['x'=>40,'y'=>20,'width'=>80,'height'=>45], 'crop_aspect_ratio'=>['width'=>16,'height'=>9], 'resize'=>['width'=>320,'height'=>180], 'fit'=>'cover', 'allow_upscale'=>true]);
    $rasterFacts = new MediaProcessingFacts('image/png', 'png', (int) filesize($rasterSource), 160, 90); $rasterProcessor = new MediaGdImageProcessor(); $generatedFacts = $rasterProcessor->write($rasterSource, $rasterOutput, $rasterFacts, $rasterRequest); $generated = imagecreatefrompng($rasterOutput); $sample = imagecolorsforindex($generated, imagecolorat($generated, 0, 0)); imagedestroy($generated); $responsiveSamples = [];
    foreach ([640, 960, 1280] as $width) { $output = tempnam(sys_get_temp_dir(), 'copot-wu6-responsive-'); $request = MediaProcessingRequest::fromArray($allowed, ['crop'=>['x'=>40,'y'=>20,'width'=>80,'height'=>45], 'crop_aspect_ratio'=>['width'=>16,'height'=>9], 'resize'=>['width'=>$width,'height'=>(int) ($width * 9 / 16)], 'fit'=>'cover', 'allow_upscale'=>true]); $facts = $rasterProcessor->write($rasterSource, $output, $rasterFacts, $request); $image = imagecreatefrompng($output); $responsiveSamples[] = [$facts->width(), $facts->height(), imagecolorsforindex($image, imagecolorat($image, 0, 0))]; imagedestroy($image); @unlink($output); }
    @unlink($rasterSource); @unlink($rasterOutput);
    $assert($generatedFacts->width() === 320 && $generatedFacts->height() === 180 && $sample['green'] > 200 && $sample['red'] < 20 && $sample['blue'] < 20 && $responsiveSamples[0][0] === 640 && $responsiveSamples[1][0] === 960 && $responsiveSamples[2][0] === 1280 && array_reduce($responsiveSamples, static fn (bool $clean, array $item): bool => $clean && $item[2]['green'] > 200 && $item[2]['red'] < 20 && $item[2]['blue'] < 20, true), 'Upscaled crop contains black or padded pixels outside the source rectangle.');
    $alphaSource=tempnam(sys_get_temp_dir(),'copot-wu6-alpha-');$alphaOutput=tempnam(sys_get_temp_dir(),'copot-wu6-alpha-');$alphaImage=imagecreatetruecolor(32,18);imagealphablending($alphaImage,false);imagesavealpha($alphaImage,true);$transparent=imagecolorallocatealpha($alphaImage,20,40,60,63);imagefill($alphaImage,0,0,$transparent);imagepng($alphaImage,$alphaSource);imagedestroy($alphaImage);$alphaFacts=new MediaProcessingFacts('image/png','png',(int)filesize($alphaSource),32,18);$alphaRequest=MediaProcessingRequest::fromArray($allowed,['crop'=>['x'=>0,'y'=>0,'width'=>32,'height'=>18],'crop_aspect_ratio'=>['width'=>16,'height'=>9],'resize'=>['width'=>64,'height'=>36],'fit'=>'cover','allow_upscale'=>true]);$rasterProcessor->write($alphaSource,$alphaOutput,$alphaFacts,$alphaRequest);$alphaResult=imagecreatefrompng($alphaOutput);$alphaPixel=imagecolorsforindex($alphaResult,imagecolorat($alphaResult,0,0));imagedestroy($alphaResult);@unlink($alphaSource);@unlink($alphaOutput);$assert(($alphaPixel['alpha']??0)>40,'RGBA PNG alpha was not preserved through crop and resize.');
    $routes = (string) file_get_contents($base . '/modules/media/routes.php'); $references = (string) file_get_contents($base . '/modules/media/Services/MediaContentReferenceService.php'); $pendingService = (string) file_get_contents($base . '/modules/media/Services/MediaPendingPreparationService.php'); $variantKeyService = (string) file_get_contents($base . '/modules/media/Services/MediaVariantKey.php'); $assert(str_contains($routes, 'context-picker') && str_contains($routes, 'image/jpeg') && !str_contains($routes, "'storage_key' =>"), 'Picker route contract or disclosure boundary is incorrect.'); $assert(str_contains($references, 'MediaVariantKey::contentSlot') && str_contains($pendingService, 'bin2hex(random_bytes(32))') && str_contains($pendingService, 'purgeExpired') && str_contains($variantKeyService, 'contentSlot'), 'Consumer-scoped pending and committed preparation boundary is incomplete.');
    $profile = (string) file_get_contents($base . '/modules/media/Services/MediaFeaturedProfile.php'); $picker = (string) file_get_contents($base . '/public/admin-assets/js/content-media-picker.js'); $show = (string) file_get_contents($base . '/modules/content/views/show.php'); $form = (string) file_get_contents($base . '/modules/content/views/admin/form.php'); $processing = (string) file_get_contents($base . '/modules/media/Services/MediaProcessingService.php'); $css = (string) file_get_contents($base . '/public/admin-assets/css/admin.css'); $assert(str_contains($profile, "'profile' => 'content.featured'") && str_contains($profile, "'responsive_widths' => [640, 960, 1280]") && str_contains($profile, "'crop_aspect_ratio' => ['width' => 16, 'height' => 9]") && str_contains($profile, "'allow_upscale' => true") && str_contains($processing, '!$request->allowUpscale()') && !str_contains($processing, '1280') && !str_contains($processing, '16 / 9'), 'Featured requirements are not isolated from the generic Media processing boundary.'); $assert(str_contains($css, '.admin-media-picker__results[hidden]') && str_contains($css, 'data-media-picker-search][hidden]') && str_contains($css, 'display: none !important'), 'Hidden Browse surfaces can be overridden by picker layout styles.'); $assert(str_contains($picker, 'processCrop') && str_contains($picker, 'Upload'), 'Picker prepare/upload flow is incomplete.'); $assert(str_contains($picker, 'beginPrepare(input.value') && str_contains($picker, 'cropImage.onload =') && str_contains($picker, 'announce(message)'), 'Re-crop does not restore the original preview or announce processing failures.'); $assert(str_contains($show, 'featuredMedia') && str_contains($show, 'srcset') && str_contains($form, 'aria-live'), 'Public featured rendering or accessible feedback contract is missing.');
    $assert(str_contains($picker, 'open(); beginPrepare(input.value') && str_contains($picker, "dialog.close();") && str_contains($picker, "image.src = item.url"), 'Picker selection does not close after processing or expose usable thumbnails.');
    $assert(str_contains($picker, 'data-media-picker-crop-y') && str_contains($picker, 'data-media-picker-crop-width') && str_contains($picker, 'data-media-picker-crop-box') && str_contains($picker, 'pointerdown') && str_contains($picker, 'fitSourceToFrame') && str_contains($picker, 'source.height / rect.height') && str_contains($picker, 'cropY.value') && !str_contains($picker, 'cropZoom') && !str_contains($picker, '1280'), 'Direct bounded crop-box positioning does not preserve natural-source geometry.');
    $assert(str_contains($picker, 'button.title =') && !str_contains($picker, 'label.textContent = item.title'), 'Browse thumbnails do not preserve accessible labels without visible captions.');
    $assert(str_contains($form, 'data-media-picker-choose-another') && str_contains($form, 'Choose another') && !str_contains($form, 'Use selected Media'), 'Picker does not expose the explicit two-stage crop flow.');
    $assert(str_contains($routes, 'use ($mediaRequireAdmin, $mediaRepository, $mediaVariants, $mediaUrl)') && str_contains($routes, '$mediaUrl('), 'Context picker did not retain the controlled Media URL dependency.');
    $assert(str_contains($picker, 'function showUnavailable()') && str_contains($picker, 'admin-media-picker__results--unavailable') && str_contains($form, 'data-media-picker-search-label') && str_contains($form, 'Select an image for this content entry.') && str_contains($form, 'Upload image') && !str_contains($form, 'multiple'), 'Picker unavailable state or single-image copy contract regressed.');
    echo "M3.8 Work Unit 6 contextual Media passed ({$assertions} assertions).", PHP_EOL;
} finally { $server->exec('DROP DATABASE IF EXISTS ' . $quoted); }
