<?php

declare(strict_types=1);

use Copot\Core\Application;
use Copot\Core\Env;
use Copot\Core\InstallerSchemaRunner;
use Copot\Core\Request;
use Copot\Core\Response;

$basePath = dirname(__DIR__);
chdir($basePath);
session_save_path(sys_get_temp_dir());
session_id('copot-wu3-' . bin2hex(random_bytes(6)));
require $basePath . '/bootstrap/autoload.php';
Env::load($basePath . '/.env');
$assertions = 0;
$assert = static function (bool $condition, string $message) use (&$assertions): void { $assertions++; if (!$condition) throw new RuntimeException($message); };
$status = static function (Response $response): int { $property = new ReflectionProperty(Response::class, 'status'); $property->setAccessible(true); return (int) $property->getValue($response); };
$body = static function (Response $response): string { $property = new ReflectionProperty(Response::class, 'content'); $property->setAccessible(true); return (string) $property->getValue($response); };
$headers = static function (Response $response): array { $property = new ReflectionProperty(Response::class, 'headers'); $property->setAccessible(true); return (array) $property->getValue($response); };
$host = (string) Env::get('DB_HOST', '127.0.0.1'); $port = (int) Env::get('DB_PORT', '3306'); $username = (string) Env::get('DB_USERNAME', 'root'); $password = (string) Env::get('DB_PASSWORD', '');
$databaseName = 'copot_wu3_' . bin2hex(random_bytes(6)); $quoted = '`' . $databaseName . '`';
$server = new PDO("mysql:host={$host};port={$port};charset=utf8mb4", $username, $password, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
$server->exec("CREATE DATABASE {$quoted} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
try {
    (new InstallerSchemaRunner($basePath . '/database/schema.sql'))->install(['host'=>$host,'port'=>$port,'databaseName'=>$databaseName,'database'=>$databaseName,'username'=>$username,'password'=>$password]);
    $_ENV['DB_DATABASE'] = $databaseName; putenv('DB_DATABASE=' . $databaseName);
    $app = new Application($basePath); $app->session()->start();
    require $basePath . '/routes/web.php'; require $basePath . '/routes/auth.php'; require $basePath . '/routes/admin.php'; require $basePath . '/routes/content_admin.php'; require $basePath . '/routes/media_admin.php'; require $basePath . '/routes/navigation_admin.php';
    $app->modules()->install('navigation'); $app->modules()->enable('navigation'); $app->moduleLoader()->loadRoutes($app);
    $db = $app->database()->connection();
    $permissions = []; foreach (['admin.access','navigation.manage'] as $slug) { $q=$db->prepare('SELECT id FROM permissions WHERE slug=:slug'); $q->execute(['slug'=>$slug]); $permissions[$slug]=(int)$q->fetchColumn(); }
    $db->exec("INSERT INTO users (name,email,password_hash,status,created_at,updated_at) VALUES ('WU3','wu3@example.test','x','active',NOW(),NOW())"); $userId=(int)$db->lastInsertId(); $db->exec("INSERT INTO roles (name,slug,created_at,updated_at) VALUES ('WU3 role','wu3-role',NOW(),NOW())"); $roleId=(int)$db->lastInsertId(); $db->exec("INSERT INTO user_roles (user_id,role_id) VALUES ({$userId},{$roleId})"); foreach($permissions as $permissionId)$db->exec("INSERT INTO role_permissions (role_id,permission_id) VALUES ({$roleId},{$permissionId})"); $app->session()->set('_copot_user_id',$userId);
    $navigation = $app->adminUrl()->childUrl('navigation'); $empty=$app->run(new Request('GET',$navigation)); $assert($status($empty)===200 && str_contains($body($empty),'Primary Navigation') && str_contains($body($empty),'Navigation item'),'Core Primary Navigation workspace did not render without Navigation Manager: status=' . $status($empty) . ' tail=' . substr($body($empty), -1000)); $assert($status($app->run(new Request('GET',$app->adminUrl()->childUrl('navigation-manager'))))===200,'Navigation Manager extension route did not coexist.'); $assert((int)$db->query("SELECT COUNT(*) FROM navigation_menus WHERE slug='primary'")->fetchColumn()===1,'Canonical primary menu was not materialized.');
    $workspaceBody = $body($empty); $assert(str_contains($workspaceBody, 'data-navigation-workspace') && substr_count($workspaceBody, 'No item selected') === 1 && str_contains($workspaceBody, 'Navigation item preview') && str_contains($workspaceBody, 'Configure this item without leaving the navigation workspace.') && !str_contains($workspaceBody, 'name="label"') && !str_contains($workspaceBody, 'name="target_choice"') && !str_contains($workspaceBody, 'Target kind') && !str_contains($workspaceBody, 'Target reference') && str_contains($workspaceBody, 'data-navigation-unselect') && str_contains($workspaceBody, 'class="admin-panel admin-navigation-workspace__detail" aria-labelledby="navigation-detail-title">'), 'Master-detail empty state is incorrect.'); $createView = $app->run(new Request('GET', $navigation, ['create' => '1'])); $assert($status($createView) === 200 && str_contains($body($createView), 'Add navigation item') && str_contains($body($createView), 'name="target_choice"') && str_contains($body($createView), 'data-navigation-dismiss') && str_contains($body($createView), 'placeholder="https://example.com, /internal-path, or #section"') && !str_contains($body($createView), 'name="content_reference"'), 'Create mode did not retain the Custom URL-specific form.');
    $token=$app->session()->csrfToken(); $create=$app->run(new Request('POST',$app->adminUrl()->childUrl('navigation/items'),[],['_token'=>$token,'label'=>'Home','target_choice'=>'custom','custom_url'=>'/','is_visible'=>'1'])); $assert($status($create)===302 && str_contains($headers($create)['Location'] ?? '', '?item='), 'Custom URL item creation failed.'); $selectedView = $app->run(new Request('GET', $navigation, ['item' => '1'])); $assert($status($selectedView) === 200 && str_contains($body($selectedView), 'Navigation item preview') && str_contains($body($selectedView), 'Home'), 'Selected item did not populate the detail card.');
    $selectedBody = $body($selectedView); $assert(str_contains($selectedBody, 'data-navigation-dismiss') && !str_contains($selectedBody, 'admin-navigation-tree__actions') && str_contains($selectedBody, 'admin-navigation-preview__actions') && str_contains($selectedBody, 'Navigation item preview') && str_contains($selectedBody, 'Configure this item without leaving the navigation workspace.') && str_contains($selectedBody, '<dt>Parent</dt><dd>Root item</dd>'), 'Selected navigation view did not expose the stable compact Preview state without row actions.');
    $customEdit=$app->run(new Request('GET',$navigation,['item'=>'1','edit'=>'1'])); $assert($status($customEdit)===200 && str_contains($body($customEdit),'name="custom_url"') && !str_contains($body($customEdit),'name="content_reference"') && !str_contains($body($customEdit),'canonical published Articles collection'), 'Custom URL Edit rendered irrelevant target fields.');
    $db->exec("INSERT INTO content (type,title,slug,excerpt,body,status,published_at,created_at,updated_at) VALUES ('article','Published','published-article','Excerpt','Body','published',NOW(),NOW(),NOW())"); $articleId=(int)$db->lastInsertId();
    $createArticle=$app->run(new Request('POST',$app->adminUrl()->childUrl('navigation/items'),[],['_token'=>$token,'label'=>'Articles','target_choice'=>'article_collection','is_visible'=>'1'])); $assert($status($createArticle)===302,'Article Collection item creation failed.');
    $createContent=$app->run(new Request('POST',$app->adminUrl()->childUrl('navigation/items'),[],['_token'=>$token,'label'=>'Story','target_choice'=>'content','content_reference'=>'published-article','is_visible'=>'1'])); $assert($status($createContent)===302,'Published Content target creation failed.');
    $articleEdit=$app->run(new Request('GET',$navigation,['item'=>'2','edit'=>'1'])); $assert($status($articleEdit)===200 && str_contains($body($articleEdit),'canonical published Articles collection') && !str_contains($body($articleEdit),'name="custom_url"') && !str_contains($body($articleEdit),'name="content_reference"'), 'Article Collection Edit rendered irrelevant target fields.');
    $contentEdit=$app->run(new Request('GET',$navigation,['item'=>'3','edit'=>'1'])); $assert($status($contentEdit)===200 && str_contains($body($contentEdit),'name="content_reference"') && !str_contains($body($contentEdit),'name="custom_url"') && !str_contains($body($contentEdit),'canonical published Articles collection'), 'Content Edit rendered irrelevant target fields.');
    $delete=$app->run(new Request('POST',$app->adminUrl()->childUrl('navigation/items/1/delete'),[],['_token'=>$token])); $assert($status($delete)===302 && ($headers($delete)['Location'] ?? '')===$navigation,'Navigation item deletion did not resolve the specific POST route.'); $assert((int)$db->query("SELECT COUNT(*) FROM navigation_items WHERE id=1")->fetchColumn()===0,'Navigation item deletion did not remove the selected item.'); $missingDelete=$app->run(new Request('POST',$app->adminUrl()->childUrl('navigation/items/999/delete'),[],['_token'=>$token])); $assert($status($missingDelete)===404,'Missing Navigation item deletion was not sanitized as 404: status=' . $status($missingDelete));
    $assert((int)$db->query("SELECT COUNT(*) FROM content WHERE type='article' AND status='published'")->fetchColumn()===1,'Published article fixture was not stored.'); $delivery = new \Copot\Core\ContentDeliveryService(new \Copot\Core\ContentRepository($app->database())); $assert(count($delivery->publishedArticles())===1,'Core Article Collection query returned no published article.'); $articles=$app->run(new Request('GET','/articles')); $assert($status($articles)===200 && str_contains($body($articles),'Published'),'Article Collection delivery failed: status=' . $status($articles) . ' tail=' . substr($body($articles), -800));
    $draftRejected=$app->run(new Request('POST',$app->adminUrl()->childUrl('navigation/items'),[],['_token'=>$token,'label'=>'Draft','target_choice'=>'content','content_reference'=>'missing','is_visible'=>'1'])); $assert($status($draftRejected)===422,'Unavailable Content target was not rejected safely.'); $csrfRejected=$app->run(new Request('POST',$app->adminUrl()->childUrl('navigation/items'),[],['label'=>'No CSRF','target_choice'=>'custom','custom_url'=>'/x'])); $assert($status($csrfRejected)===419,'CSRF boundary did not reject missing token.');
    $navigationCss=(string)file_get_contents($basePath . '/public/admin-assets/css/admin.css'); $navigationScript=(string)file_get_contents($basePath . '/public/admin-assets/js/navigation-admin.js'); $assert(str_contains($navigationCss, '.admin-navigation-tree__row:hover') && str_contains($navigationCss, 'color-mix(in srgb, var(--admin-color-primary) 7%, var(--admin-color-surface))') && str_contains($navigationCss, '.admin-navigation-preview__actions') && str_contains($navigationCss, '.admin-form__actions {') && str_contains($navigationScript, 'data-navigation-unselect') && str_contains($navigationScript, 'targetFields.replaceChildren()'), 'Navigation acceptance presentation affordances are incomplete.');
    echo "WU3 Core Primary Navigation baseline passed ({$assertions} assertions)." . PHP_EOL;
} finally { if (isset($app)) { $connection = new ReflectionProperty(\Copot\Core\Database::class, 'connection'); $connection->setAccessible(true); $connection->setValue($app->database(), null); } unset($app, $db, $navigationService, $navigationRepository, $contentRepository, $primaryNavigation, $delivery); gc_collect_cycles(); $serverId=(int)$server->query('SELECT CONNECTION_ID()')->fetchColumn(); $connections=$server->prepare('SELECT ID FROM information_schema.PROCESSLIST WHERE DB=:database'); $connections->execute(['database'=>$databaseName]); foreach($connections->fetchAll(PDO::FETCH_COLUMN) as $connectionId) if((int)$connectionId!==$serverId)$server->exec('KILL CONNECTION ' . (int)$connectionId); $server->exec("DROP DATABASE IF EXISTS {$quoted}"); }
