<?php
$escape = static fn (mixed $value): string => htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
$values = is_array($values ?? null) ? $values : [];
$errors = is_array($errors ?? null) ? $errors : [];
$media = is_array($media ?? null) ? $media : [];
$areas = ['identity' => 'Site Identity', 'system' => 'System', 'security' => 'Security', 'email' => 'Email', 'modules' => 'Modules', 'health' => 'System Health'];
$siteAssets = $siteAssets ?? null;
$settingsFormId = 'site-settings-identity-form';
?>
<section class="admin-panel admin-settings-page site-settings-page" aria-labelledby="site-settings-title" aria-describedby="site-settings-description" data-site-settings data-settings-page data-initial-tab="site-settings-identity">
    <header class="admin-panel__header"><div class="admin-panel__heading"><p class="admin-panel__description" id="site-settings-description">Configure the site identity and baseline appearance.</p></div></header>
    <div class="admin-settings-tabs-wrap">
        <div class="admin-settings-tabs" role="tablist" aria-label="Site Settings areas">
            <?php foreach ($areas as $id => $label): $tabId = 'site-settings-' . $id; ?><button class="admin-settings-tab<?= $id === 'identity' ? ' is-active' : '' ?>" id="<?= $escape($tabId . '-tab') ?>" type="button" role="tab" aria-selected="<?= $id === 'identity' ? 'true' : 'false' ?>" aria-controls="<?= $escape($tabId) ?>" tabindex="<?= $id === 'identity' ? '0' : '-1' ?>" data-settings-tab="<?= $escape($tabId) ?>"><span><?= $escape($label) ?></span><span class="admin-settings-tab__dirty" aria-hidden="true" hidden>•</span></button><?php endforeach; ?>
        </div>
    </div>
    <div class="admin-panel__body">
        <?php if (($notice ?? null) !== null): ?><div class="admin-alert admin-alert--success" role="status"><?= $escape($notice) ?></div><?php endif; ?>
        <?php if ($errors !== []): ?><div class="admin-alert admin-alert--danger" role="alert">Some Site Settings could not be saved.</div><?php endif; ?>
        <section class="admin-settings-panel" id="site-settings-identity" role="tabpanel" aria-labelledby="site-settings-identity-tab" data-settings-panel="site-settings-identity">
            <div class="site-settings-identity-layout" data-settings-dirty-form>
                <form method="post" action="<?= $escape($path) ?>" class="admin-form site-settings-identity-form" id="<?= $settingsFormId ?>">
                    <input type="hidden" name="_token" value="<?= $escape($csrfToken) ?>">
                </form>
                <div class="site-settings-identity__settings">
                    <fieldset class="admin-fieldset site-settings-identity__general"><legend class="admin-fieldset__legend">General</legend>
                        <div class="admin-settings-field-grid admin-settings-field-grid--single"><div class="admin-field"><label class="admin-field__label" for="site_name">Site Name</label><input id="site_name" name="site_name" form="<?= $settingsFormId ?>" type="text" value="<?= $escape($values['name'] ?? '') ?>" required><p class="admin-field__error"><?= $escape($errors['site.name'] ?? '') ?></p></div><div class="admin-field"><label class="admin-field__label" for="site_tagline">Site Tagline</label><input id="site_tagline" name="site_tagline" form="<?= $settingsFormId ?>" type="text" value="<?= $escape($values['tagline'] ?? '') ?>"><p class="admin-field__error"><?= $escape($errors['site.tagline'] ?? '') ?></p></div></div>
                    </fieldset>
                    <fieldset class="admin-fieldset site-settings-identity__localization"><legend class="admin-fieldset__legend">Localization</legend><div class="admin-settings-field-grid"><?php foreach ([['locale','Locale',$locales ?? []],['timezone','Timezone',$timezones ?? []],['date_format','Date Format',$dateFormats ?? []],['time_format','Time Format',$timeFormats ?? []]] as [$key,$label,$options]): ?><div class="admin-field"><label class="admin-field__label" for="<?= $key ?>"><?= $escape($label) ?></label><select id="<?= $key ?>" name="<?= $key ?>" form="<?= $settingsFormId ?>" required><?php foreach ($options as $option): ?><option value="<?= $escape($option) ?>"<?= ($values[$key] ?? '') === $option ? ' selected' : '' ?>><?= $escape($option) ?></option><?php endforeach; ?></select></div><?php endforeach; ?></div></fieldset>
                    <fieldset class="admin-fieldset site-settings-identity__appearance"><legend class="admin-fieldset__legend">Appearance</legend><div class="admin-field"><label class="admin-field__label" for="main_color_hex">Main Color</label><div class="admin-settings-color-control"><input class="admin-settings-color-input" id="main_color" name="main_color" form="<?= $settingsFormId ?>" type="color" value="<?= $escape($values['main_color'] ?? '#1769e0') ?>" required data-main-color-picker aria-label="Main Color picker"><input class="admin-settings-color-hex" id="main_color_hex" form="<?= $settingsFormId ?>" type="text" value="<?= $escape($values['main_color'] ?? '#1769e0') ?>" inputmode="text" maxlength="7" pattern="#[0-9A-Fa-f]{6}" required data-main-color-hex aria-label="Main Color HEX value" aria-describedby="main-color-help"></div><p class="admin-field__help" id="main-color-help">Your site’s primary brand color. Webcore derives bounded presentation variants automatically.</p></div></fieldset>
                </div>
                <div class="site-settings-identity__media">
                    <fieldset class="admin-fieldset site-settings-identity__assets"><legend class="admin-fieldset__legend">Site Assets</legend><div class="site-settings-asset-stack">
                    <?php foreach ([['logo','Logo','PNG, JPG, or WebP. Maximum 2 MB; maximum 4096 × 4096 px.','image/png,image/jpeg,image/webp','logoUploadAction','logoRemoveAction'],['favicon','Favicon','PNG or ICO. Maximum 512 KB; maximum 512 × 512 px.','image/png,image/x-icon','faviconUploadAction','faviconRemoveAction']] as [$slot,$label,$helper,$accept,$uploadAction,$removeAction]): ?>
                        <div class="site-settings-asset-block">
                            <span class="admin-field__label"><?= $escape($label) ?></span>
                            <p class="admin-field__help"><?= $escape($helper) ?></p>
                            <div class="site-settings-asset-preview-row">
                                <div class="admin-asset-preview site-settings-asset-preview<?= $slot === 'favicon' ? ' site-settings-asset-preview--favicon' : '' ?>">
                                    <?php if ($siteAssets?->url($slot)): ?><img src="<?= $escape($siteAssets->url($slot)) ?>" alt="Current <?= $escape(strtolower($label)) ?>"><?php else: ?><span class="site-settings-asset-preview__empty">No <?= $escape(strtolower($label)) ?> selected.</span><?php endif; ?>
                                </div>
                                <div class="site-settings-asset-actions">
                                    <?php if (!$siteAssets?->url($slot)): ?><span class="admin-field__label">Choose <?= $escape($label) ?></span><form class="admin-field" method="post" action="<?= $escape($$uploadAction) ?>" enctype="multipart/form-data"><input type="hidden" name="_token" value="<?= $escape($csrfToken) ?>"><input type="file" name="site_asset" accept="<?= $escape($accept) ?>" required><div class="admin-actions"><button class="admin-button admin-button--secondary" type="submit">Upload</button></div></form><?php else: ?><form class="admin-actions" method="post" action="<?= $escape($$removeAction) ?>"><input type="hidden" name="_token" value="<?= $escape($csrfToken) ?>"><button class="admin-button admin-button--secondary" type="submit">Remove</button></form><?php endif; ?>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
                <fieldset class="admin-fieldset site-settings-identity__hero"><legend class="admin-fieldset__legend">Homepage</legend><div class="admin-field"><span class="admin-field__label">Hero Image</span><input id="hero_media" name="hero_media" form="<?= $settingsFormId ?>" type="hidden" value="<?= $escape($values['hero_media'] ?? '') ?>" data-site-settings-hero-input><p class="admin-field__help" data-site-settings-hero-status aria-live="polite">Use a high-resolution supported image with important content near the center. The Built-in Public View crops the image responsively; select an image from Core Media and save Site Settings to keep the selection.</p><div class="admin-media-picker__selected site-settings-hero-preview" data-site-settings-hero-selected><span class="site-settings-hero-preview__empty"<?= !empty($values['hero_media']) ? ' hidden' : '' ?>>No Hero Image selected.</span><?php if (!empty($values['hero_media'])): ?><img src="<?= $escape(is_callable($mediaUrl ?? null) ? $mediaUrl((int) $values['hero_media']) : '/media/' . (int) $values['hero_media']) ?>" alt="Homepage Hero Image"><?php endif; ?></div><div class="admin-actions"><button class="admin-button admin-button--secondary" type="button" data-site-settings-hero-open>Choose</button><button class="admin-button admin-button--secondary" type="button" data-site-settings-hero-clear <?= empty($values['hero_media']) ? 'hidden' : '' ?>>Clear</button></div><p class="admin-field__error"><?= $escape($errors['hero_media'] ?? '') ?></p><dialog class="admin-media-picker" data-site-settings-hero-picker data-picker-url="<?= $escape($mediaPickerUrl ?? '') ?>" data-upload-url="<?= $escape($mediaPickerUploadUrl ?? '') ?>" data-csrf-token="<?= $escape($csrfToken) ?>" data-can-upload="<?= !empty($canMediaUpload) ? '1' : '0' ?>" aria-labelledby="site-settings-hero-picker-title"><div class="admin-media-picker__panel"><h3 id="site-settings-hero-picker-title">Choose Homepage Hero Image</h3><p class="admin-field__help">Choose a supported image from Core Media.</p><div class="admin-media-picker__results" data-site-settings-hero-results aria-live="polite"></div><?php if (!empty($canMediaUpload)): ?><div class="admin-field"><label class="admin-field__label" for="site-settings-hero-upload">Upload New</label><input id="site-settings-hero-upload" type="file" accept="image/jpeg,image/png,image/webp" data-site-settings-hero-upload></div><div class="admin-actions"><button class="admin-button admin-button--primary" type="button" data-site-settings-hero-upload-button>Upload</button><button class="admin-button admin-button--secondary" type="button" data-site-settings-hero-close>Cancel</button></div><?php else: ?><div class="admin-actions"><button class="admin-button admin-button--secondary" type="button" data-site-settings-hero-close>Cancel</button></div><?php endif; ?></div></dialog></div></fieldset>
                <div class="admin-actions admin-form__actions site-settings-identity__save"><button class="admin-button admin-button--primary" type="submit" form="<?= $settingsFormId ?>">Save Site Settings</button></div>
            </div>
        </section>
        <?php foreach (['system' => 'System settings are available in a later WU4 batch.', 'security' => 'Security settings are not configurable in this build.', 'email' => 'Email settings are not configurable in this build.', 'modules' => 'Module operations are available in a later WU4 batch.', 'health' => 'System Health presentation is available in a later WU4 batch.'] as $id => $message): ?><section class="admin-settings-panel" id="site-settings-<?= $id ?>" role="tabpanel" aria-labelledby="site-settings-<?= $id ?>-tab" data-settings-panel="site-settings-<?= $id ?>" hidden><header class="admin-settings-panel__header"><h3><?= $escape($areas[$id]) ?></h3></header><div class="admin-empty-state"><h4>Not configurable in Batch 1</h4><p><?= $escape($message) ?></p></div></section><?php endforeach; ?>
    </div>
</section>
<script src="<?= $escape(is_callable($url ?? null) ? $url('/admin-assets/js/admin-settings.js') : '/admin-assets/js/admin-settings.js') ?>" defer></script>
<script src="<?= $escape(is_callable($url ?? null) ? $url('/admin-assets/js/site-settings-hero-picker.js?v=wu4-b1-2') : '/admin-assets/js/site-settings-hero-picker.js?v=wu4-b1-2') ?>" defer></script>
<script src="<?= $escape(is_callable($url ?? null) ? $url('/admin-assets/js/site-settings-color.js?v=wu4-b1-1') : '/admin-assets/js/site-settings-color.js?v=wu4-b1-1') ?>" defer></script>
