<?php

use Copot\Core\Content;
use Copot\Core\ContentRepository;
use Copot\Core\NavigationRepository;
use Copot\Core\NavigationService;
use Copot\Core\PrimaryNavigationAdmin;
use Copot\Core\Response;

$navigationRepository = new NavigationRepository($app->database());
$navigationService = new NavigationService($app->database(), $navigationRepository);
$contentRepository = new ContentRepository($app->database());
$primaryNavigation = new PrimaryNavigationAdmin($app->database(), $navigationRepository, $navigationService, $contentRepository);
$navigationPath = $app->adminUrl()->childUrl('navigation');
$itemPath = static fn (string $suffix = ''): string => $app->adminUrl()->childUrl('navigation/items' . $suffix);
$requireNavigation = static function ($request) use ($app): mixed { if (!$app->auth()->check()) return Response::redirect($app->adminUrl()->baseUrl()); $user = $app->auth()->user(); if (!$user?->can('admin.access') || !$user->can('navigation.manage')) return $app->adminErrors()->response($request, 403); return $user; };
$id = static fn (mixed $value): ?int => is_scalar($value) && preg_match('/^[1-9][0-9]*$/D', (string) $value) === 1 ? (int) $value : null;
$subtreeHeight = static function (array $items, ?int $current): int { if ($current === null) return 1; $children = []; foreach ($items as $item) $children[$item->parentId() ?? 0][] = $item->id(); $max = 1; $stack = [[$current, 1]]; while ($stack) { [$id, $depth] = array_pop($stack); $max = max($max, $depth); foreach ($children[$id] ?? [] as $childId) $stack[] = [$childId, $depth + 1]; } return $max; };
$parents = static function (array $items, ?int $current = null, int $height = 1): array { $byParent = []; foreach ($items as $item) $byParent[$item->parentId() ?? 0][] = $item; $excluded = []; if ($current !== null) { $stack = [$current]; while ($stack) { $currentId = array_pop($stack); if (isset($excluded[$currentId])) continue; $excluded[$currentId] = true; foreach ($byParent[$currentId] ?? [] as $child) $stack[] = $child->id(); } } $result = []; $walk = function (int $parent, int $depth) use (&$walk, &$result, $byParent, $excluded, $height): void { foreach ($byParent[$parent] ?? [] as $item) { if (isset($excluded[$item->id()])) continue; if ($depth + $height + 1 <= 5) $result[] = ['item' => $item, 'depth' => $depth]; $walk($item->id(), $depth + 1); } }; $walk(0, 0); return $result; };
$tree = static function (array $items): array { $children = []; foreach ($items as $item) $children[$item->parentId() ?? 0][] = $item; $walk = function (int $parent, int $depth) use (&$walk, $children): array { $result = []; foreach ($children[$parent] ?? [] as $item) $result[] = ['item' => $item, 'depth' => $depth, 'children' => $walk($item->id(), $depth + 1)]; return $result; }; return $walk(0, 0); };
$blankItem = static fn (): array => ['label' => '', 'parent_id' => null, 'target_choice' => 'link', 'content_reference' => '', 'custom_url' => '', 'is_visible' => true];
$viewData = static function (array $base) use ($app, $contentRepository, $navigationPath): array { $published = $contentRepository->workspace(['status' => 'published'], 100, 0)['items']; return $base + ['csrfToken' => $app->csrf()->token(), 'navigationPath' => $navigationPath, 'contentOptions' => array_values(array_filter($published, static fn (Content $content): bool => in_array($content->type(), ['page', 'article'], true)))]; };
$render = static function ($request, $user, array $data, int $status = 200) use ($app, $navigationPath): Response { return Response::html($app->adminPageRenderer()->render('Primary Navigation', $app->view()->render('admin/navigation/items', $data), $user, $app->csrf()->token(), $request->path(), ['description' => 'Manage the Webcore primary menu hierarchy and targets.', 'bar' => null, 'surface' => 'transparent', 'spacing' => 'default'], [['label' => 'Navigation', 'url' => $navigationPath]]), $status); };
$app->adminNavigation()->add('Navigation', $navigationPath, ['navigation.manage'], 'navigation', 60);

$app->router()->get($navigationPath, function ($request) use ($app, $requireNavigation, $primaryNavigation, $navigationService, $navigationPath, $parents, $subtreeHeight, $tree, $blankItem, $viewData, $render, $id, $itemPath): Response { $user = $requireNavigation($request); if ($user instanceof Response) return $user; try { $menu = $primaryNavigation->ensureMenu(); $items = $navigationService->itemsForMenu($menu->id()); $selectedId = $id($request->input('item')); $selected = $selectedId === null ? null : $navigationService->findItem($selectedId); if ($selected !== null && $selected->menuId() !== $menu->id()) return $app->adminErrors()->response($request, 404); $creating = $request->input('create') === '1'; $editing = $request->input('edit') === '1'; $formItem = $blankItem(); if ($selected !== null) $formItem = ['label' => $selected->label(), 'parent_id' => $selected->parentId(), 'target_choice' => in_array($selected->targetKind(), ['custom', 'link'], true) ? 'link' : $selected->targetKind(), 'content_reference' => $selected->targetKind() === 'content' ? (string) $selected->targetReference() : '', 'custom_url' => $selected->customUrl() ?? '', 'is_visible' => $selected->isVisible()]; return $render($request, $user, $viewData(['menu' => $menu, 'items' => $items, 'tree' => $tree($items), 'selected' => $selected, 'creating' => $creating, 'editing' => $editing, 'formItem' => $formItem, 'parents' => $parents($items, $selected?->id(), $subtreeHeight($items, $selected?->id())), 'formAction' => $selected ? $itemPath('/' . $selected->id()) : $itemPath(''), 'errors' => [], 'itemPath' => $itemPath])); } catch (Throwable) { return $app->adminErrors()->response($request, 503); } });
$data = static function ($request, int $menuId): array { $read = static fn (string $field): string => is_scalar($request->post($field, '')) ? trim((string) $request->post($field, '')) : ''; $choice = strtolower($read('target_choice')); $base = ['menu_id' => $menuId, 'parent_id' => $read('parent_id') === '' ? null : (int) $read('parent_id'), 'label' => $read('label'), 'is_visible' => $request->post('is_visible') === '1']; if ($choice === 'link' || $choice === 'custom') return $base + ['target_kind' => 'link', 'target_reference' => null, 'custom_url' => $read('custom_url')]; if ($choice === 'navigation_group') return $base + ['target_kind' => 'navigation_group', 'target_reference' => null, 'custom_url' => null]; if ($choice === 'article_collection') return $base + ['target_kind' => 'article_collection', 'target_reference' => 'articles', 'custom_url' => null]; return $base + ['target_kind' => 'content', 'target_reference' => $read('content_reference'), 'custom_url' => null]; };
$saveItem = static function ($request, ?array $params = null) use ($app, $requireNavigation, $primaryNavigation, $navigationService, $data, $navigationPath, $parents, $subtreeHeight, $tree, $blankItem, $viewData, $render, $itemPath): Response { $user = $requireNavigation($request); if ($user instanceof Response) return $user; if ($app->csrf()->validateOrReject($request) instanceof Response) return $app->adminErrors()->response($request, 419); try { $menu = $primaryNavigation->ensureMenu(); $payload = $data($request, $menu->id()); $itemId = isset($params['item']) ? (int) $params['item'] : null; if ($itemId !== null) $primaryNavigation->updateItem($itemId, $payload); else $itemId = $primaryNavigation->createItem($payload); return Response::redirect($navigationPath . '?item=' . $itemId); } catch (InvalidArgumentException $exception) { try { $menu = $primaryNavigation->ensureMenu(); $items = $navigationService->itemsForMenu($menu->id()); $payload = $data($request, $menu->id()); $payload['target_choice'] = $payload['target_kind']; $selectedId = isset($params['item']) ? (int) $params['item'] : null; return $render($request, $user, $viewData(['menu' => $menu, 'items' => $items, 'tree' => $tree($items), 'selected' => null, 'creating' => $selectedId === null, 'editing' => $selectedId !== null, 'formItem' => $payload, 'parents' => $parents($items, $selectedId, $subtreeHeight($items, $selectedId)), 'formAction' => $itemPath($selectedId === null ? '' : '/' . $selectedId), 'errors' => ['form' => [$exception->getMessage()]], 'itemPath' => $itemPath]), 422); } catch (Throwable) { return $app->adminErrors()->response($request, 503); } } catch (Throwable) { return $app->adminErrors()->response($request, 503); } };
$app->router()->get($itemPath('/create'), fn ($request) => Response::redirect($navigationPath . '?create=1'));
$app->router()->get($itemPath('/{item}/edit'), function ($request, array $params) use ($app, $requireNavigation, $navigationService, $primaryNavigation, $navigationPath, $id): Response { $user = $requireNavigation($request); if ($user instanceof Response) return $user; $itemId = $id($params['item'] ?? null); if ($itemId === null) return $app->adminErrors()->response($request, 404); try { $menu = $primaryNavigation->ensureMenu(); $item = $navigationService->findItem($itemId); if ($item === null || $item->menuId() !== $menu->id()) return $app->adminErrors()->response($request, 404); return Response::redirect($navigationPath . '?item=' . $itemId); } catch (Throwable) { return $app->adminErrors()->response($request, 503); } });
$app->router()->post($itemPath(''), fn ($request) => $saveItem($request));
$app->router()->post($itemPath('/{item}/delete'), function ($request, array $params) use ($app, $requireNavigation, $navigationService, $navigationPath, $id): Response { $user = $requireNavigation($request); if ($user instanceof Response) return $user; if ($app->csrf()->validateOrReject($request) instanceof Response) return $app->adminErrors()->response($request, 419); $itemId = $id($params['item'] ?? null); if ($itemId === null) return $app->adminErrors()->response($request, 404); try { $navigationService->deleteItem($itemId); return Response::redirect($navigationPath); } catch (InvalidArgumentException) { return $app->adminErrors()->response($request, 404); } catch (Throwable) { return $app->adminErrors()->response($request, 503); } });
$app->router()->post($itemPath('/reorder'), function ($request) use ($app, $requireNavigation, $primaryNavigation, $navigationService, $navigationPath): Response { $user = $requireNavigation($request); if ($user instanceof Response) return $user; if ($app->csrf()->validateOrReject($request) instanceof Response) return $app->adminErrors()->response($request, 419); $parent = $request->post('parent_id', ''); $moved = $request->post('moved_id', ''); $ids = $request->post('item_ids', null); if (($parent !== '' && (!is_scalar($parent) || !preg_match('/^[1-9][0-9]*$/D', (string) $parent))) || !is_scalar($moved) || !preg_match('/^[1-9][0-9]*$/D', (string) $moved) || !is_array($ids)) return $app->adminErrors()->response($request, 422); try { $menu = $primaryNavigation->ensureMenu(); $navigationService->moveItem($menu->id(), (int) $moved, $parent === '' ? null : (int) $parent, array_map('intval', $ids)); return Response::redirect($navigationPath); } catch (InvalidArgumentException) { return $app->adminErrors()->response($request, 422); } catch (Throwable) { return $app->adminErrors()->response($request, 503); } });
$app->router()->post($itemPath('/{item}'), function ($request, array $params) use ($saveItem, $id): Response { $itemId = $id($params['item'] ?? null); return $itemId === null ? Response::content('404 Not Found', 404) : $saveItem($request, ['item' => $itemId]); });
