<section class="admin-panel" aria-labelledby="navigation-items-title">
    <header class="admin-panel__header"><div class="admin-panel__heading"><h2 class="admin-panel__title" id="navigation-items-title"><?= htmlspecialchars($menu->name(), ENT_QUOTES, 'UTF-8') ?> items</h2><p class="admin-panel__description">Arrange up to five hierarchy levels, control visibility, and manage target references.</p></div><div class="admin-actions"><a class="admin-button admin-button--secondary" href="<?= htmlspecialchars($adminUrl('navigation'), ENT_QUOTES, 'UTF-8') ?>">All menus</a><a class="admin-button admin-button--primary" href="<?= htmlspecialchars($adminUrl('navigation/' . $menu->id() . '/items/create'), ENT_QUOTES, 'UTF-8') ?>">Create item</a></div></header>
    <div class="admin-panel__body">
        <?php if (($notice ?? null) !== null): ?><div class="admin-alert admin-alert--success" role="status"><?= htmlspecialchars($notice, ENT_QUOTES, 'UTF-8') ?></div><?php endif; ?>
        <?php if ($items === []): ?><div class="admin-empty-state"><h3 class="admin-empty-state__title">No navigation items yet</h3><p class="admin-empty-state__description">Create the first item for this menu.</p><div class="admin-empty-state__actions"><a class="admin-button admin-button--primary" href="<?= htmlspecialchars($adminUrl('navigation/' . $menu->id() . '/items/create'), ENT_QUOTES, 'UTF-8') ?>">Create item</a></div></div>
        <?php else: ?><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th scope="col">Item</th><th scope="col">Target</th><th scope="col">Visibility</th><th scope="col">Actions</th></tr></thead><tbody>
            <?php foreach ($items as $entry): $item = $entry['item']; $actions = $reorderActions[$item->id()] ?? []; ?>
                <tr><td><strong class="admin-table-primary"><?= str_repeat('— ', (int) $entry['depth']) . htmlspecialchars($item->label(), ENT_QUOTES, 'UTF-8') ?></strong><?php if ($item->parentId() === null): ?> <span class="admin-badge admin-badge--info">Root</span><?php endif; ?></td>
                    <td><span class="admin-table-meta admin-table-wrap-anywhere"><?= htmlspecialchars($item->targetKind() === 'custom' ? (string) $item->customUrl() : $item->targetKind() . ':' . (string) $item->targetReference(), ENT_QUOTES, 'UTF-8') ?></span></td>
                    <td><?= $item->isVisible() ? '<span class="admin-badge admin-badge--success">Visible</span>' : '<span class="admin-badge">Hidden</span>' ?></td>
                    <td><div class="admin-row-actions"><a class="admin-button admin-button--link" href="<?= htmlspecialchars($adminUrl('navigation/' . $menu->id() . '/items/' . $item->id() . '/edit'), ENT_QUOTES, 'UTF-8') ?>">Edit</a><?php foreach (['up' => 'Move up', 'down' => 'Move down'] as $direction => $label): if (isset($actions[$direction])): ?><form class="admin-inline-form" method="post" action="<?= htmlspecialchars($adminUrl('navigation/' . $menu->id() . '/items/reorder'), ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="_token" value="<?= htmlspecialchars($csrfToken ?? '', ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="parent_id" value="<?= htmlspecialchars((string) $actions[$direction]['parent_id'], ENT_QUOTES, 'UTF-8') ?>"><?php foreach ($actions[$direction]['item_ids'] as $id): ?><input type="hidden" name="item_ids[]" value="<?= htmlspecialchars((string) $id, ENT_QUOTES, 'UTF-8') ?>"><?php endforeach; ?><button class="admin-button admin-button--link" type="submit"><?= htmlspecialchars($label, ENT_QUOTES, 'UTF-8') ?></button></form><?php endif; endforeach; ?><form class="admin-inline-form" method="post" action="<?= htmlspecialchars($adminUrl('navigation/' . $menu->id() . '/items/' . $item->id() . '/delete'), ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="_token" value="<?= htmlspecialchars($csrfToken ?? '', ENT_QUOTES, 'UTF-8') ?>"><button class="admin-button admin-button--link admin-action-danger" type="submit">Delete</button></form></div></td>
                </tr>
            <?php endforeach; ?></tbody></table></div><?php endif; ?>
    </div>
</section>
