<section class="admin-panel" aria-labelledby="navigation-item-form-title">
    <header class="admin-panel__header"><div class="admin-panel__heading"><h2 class="admin-panel__title" id="navigation-item-form-title">Item details</h2><p class="admin-panel__description"><?= htmlspecialchars($heading ?? 'Item details', ENT_QUOTES, 'UTF-8') ?> in <?= htmlspecialchars($menu->name(), ENT_QUOTES, 'UTF-8') ?>.</p></div></header>
    <div class="admin-panel__body">
        <?php if ($errors !== []): ?><div class="admin-alert admin-alert--danger" role="alert" id="navigation-item-errors"><strong>Please correct the following errors.</strong><ul class="admin-alert__list"><?php foreach ($errors as $fieldErrors): foreach ((array) $fieldErrors as $error): ?><li><?= htmlspecialchars($error, ENT_QUOTES, 'UTF-8') ?></li><?php endforeach; endforeach; ?></ul></div><?php endif; ?>
        <form class="admin-form" method="post" action="<?= htmlspecialchars($formAction, ENT_QUOTES, 'UTF-8') ?>">
            <input type="hidden" name="_token" value="<?= htmlspecialchars($csrfToken ?? '', ENT_QUOTES, 'UTF-8') ?>">
            <div class="admin-field"><label class="admin-field__label" for="label">Label</label><input id="label" name="label" type="text" required value="<?= htmlspecialchars($item['label'] ?? '', ENT_QUOTES, 'UTF-8') ?>"></div>
            <div class="admin-field"><label class="admin-field__label" for="parent_id">Parent item</label><select id="parent_id" name="parent_id"><option value="">Root item (no parent)</option><?php foreach ($parentCandidates as $candidate): $candidateItem = $candidate['item']; ?><option value="<?= htmlspecialchars((string) $candidateItem->id(), ENT_QUOTES, 'UTF-8') ?>" <?= (string) ($item['parent_id'] ?? '') === (string) $candidateItem->id() ? 'selected' : '' ?>><?= str_repeat('— ', (int) $candidate['depth']) . htmlspecialchars($candidateItem->label(), ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></div>
            <fieldset class="admin-fieldset"><legend>Target</legend><div class="admin-field"><label class="admin-field__label" for="target_mode">Target type</label><select id="target_mode" name="target_mode"><option value="custom" <?= ($item['target_mode'] ?? 'custom') === 'custom' ? 'selected' : '' ?>>Custom URL</option><option value="provider" <?= ($item['target_mode'] ?? '') === 'provider' ? 'selected' : '' ?>>Provider reference</option></select></div><div class="admin-field"><label class="admin-field__label" for="custom_url">Custom URL</label><input id="custom_url" name="custom_url" type="text" value="<?= htmlspecialchars($item['custom_url'] ?? '', ENT_QUOTES, 'UTF-8') ?>"><p class="admin-field__help">Use a local path, fragment, or absolute HTTP(S) URL.</p></div><div class="admin-field"><label class="admin-field__label" for="target_kind">Provider kind</label><input id="target_kind" name="target_kind" type="text" value="<?= htmlspecialchars($item['target_kind'] ?? '', ENT_QUOTES, 'UTF-8') ?>" placeholder="content"></div><div class="admin-field"><label class="admin-field__label" for="target_reference">Provider reference</label><input id="target_reference" name="target_reference" type="text" value="<?= htmlspecialchars($item['target_reference'] ?? '', ENT_QUOTES, 'UTF-8') ?>"><p class="admin-field__help">Provider references are stored explicitly; unavailable targets fail closed during resolution.</p></div></fieldset>
            <div class="admin-field"><label class="admin-check-option"><input type="checkbox" name="is_visible" value="1" <?= !empty($item['is_visible']) ? 'checked' : '' ?>> <span>Visible</span></label></div>
            <div class="admin-actions admin-form__actions"><a class="admin-button admin-button--secondary" href="<?= htmlspecialchars($adminUrl('navigation/' . $menu->id() . '/items'), ENT_QUOTES, 'UTF-8') ?>">Cancel</a><button class="admin-button admin-button--primary" type="submit"><?= htmlspecialchars($submitLabel ?? 'Save item', ENT_QUOTES, 'UTF-8') ?></button></div>
        </form>
    </div>
</section>
