<?php

final class MediaGdImageProcessor implements MediaImageProcessor
{
    private const MAX_WIDTH = 4096; private const MAX_HEIGHT = 4096; private const MAX_PIXELS = 16777216; private const PNG_COMPRESSION = 6;
    public function __construct(private $capabilityProbe = null, private $exifReader = null, private string $version = 'gd-r1', private $exifCapabilityProbe = null) {}
    public function processorVersion(): string { return $this->version; }
    public function normalizedDimensions(string $path, MediaProcessingFacts $facts): array { $orientation=$this->orientation($path,$facts->mimeType()); return in_array($orientation,[5,6,7,8],true)?[$facts->height(),$facts->width()]:[$facts->width(),$facts->height()]; }
    public function write(string $sourcePath, string $destinationPath, MediaProcessingFacts $sourceFacts, MediaProcessingRequest $request): MediaProcessingFacts
    {
        $this->requireCapability($sourceFacts->mimeType()); $this->preflight($sourceFacts, $request); $source=$this->decode($sourcePath,$sourceFacts->mimeType()); $source=$this->normalize($source,$this->orientation($sourcePath,$sourceFacts->mimeType()));
        $width=imagesx($source); $height=imagesy($source); if ($request->crop() !== null) $source=$this->crop($source,$request->crop()); elseif ($request->aspectRatio() !== null) $source=$this->aspectCrop($source,$request->aspectRatio());
        if ($request->rotation() !== 0) $source=$this->rotate($source,$request->rotation());
        [$targetWidth,$targetHeight]=[$request->resizeWidth(),$request->resizeHeight()]; if ($targetWidth !== null || $targetHeight !== null) $source=$this->resize($source,$targetWidth,$targetHeight,$request->fit());
        $format=$request->outputFormat() ?? $sourceFacts->extension(); if (!in_array($format,['jpg','png','webp'],true)) throw new MediaProcessingValidationException('Output format is invalid.'); $this->validateBounds(imagesx($source),imagesy($source)); $source=$this->prepareAlpha($source,$format); $width=imagesx($source); $height=imagesy($source); $this->encode($source,$destinationPath,$format,$request->quality()); imagedestroy($source);
        $size=filesize($destinationPath); if ($size === false || $size > 16777216) throw new MediaProcessingValidationException('Generated image size is invalid.'); return new MediaProcessingFacts($this->mime($format),$format,$size,$width,$height);
    }
    private function requireCapability(string $mime): void { $available=$this->capabilityProbe ? (bool) ($this->capabilityProbe)($mime) : extension_loaded('gd'); if (!$available) throw new MediaProcessingCapabilityException('Image processing capability is unavailable.'); if ($mime==='image/jpeg' && !($this->exifCapabilityProbe ? (bool) ($this->exifCapabilityProbe)() : function_exists('exif_read_data')) && $this->exifReader===null) throw new MediaProcessingCapabilityException('JPEG orientation capability is unavailable.'); $required=['image/jpeg'=>['imagecreatefromjpeg','imagejpeg'],'image/png'=>['imagecreatefrompng','imagepng'],'image/webp'=>['imagecreatefromwebp','imagewebp']][$mime]??[]; foreach($required as $fn)if(!function_exists($fn))throw new MediaProcessingCapabilityException('Image processing capability is unavailable.'); }
    private function decode(string $path,string $mime){$fn=['image/jpeg'=>'imagecreatefromjpeg','image/png'=>'imagecreatefrompng','image/webp'=>'imagecreatefromwebp'][$mime]??null;if(!$fn||!is_resource($image=$fn($path))&&!(is_object($image)))throw new MediaProcessingValidationException('Source image could not be decoded.');if($mime!=='image/jpeg'){imagealphablending($image,false);imagesavealpha($image,true);}return $image;}
    private function orientation(string $path,string $mime): int { if($mime!=='image/jpeg')return 1; $value=$this->exifReader?($this->exifReader)($path):(@exif_read_data($path,false,false)['Orientation']??1); if(!is_int($value)||!in_array($value,[1,2,3,4,5,6,7,8],true))throw new MediaProcessingValidationException('JPEG orientation is invalid.');return $value; }
    private function normalize($image,int $orientation){if($orientation===2)imageflip($image,IMG_FLIP_HORIZONTAL);elseif($orientation===3)$image=$this->rotateImage($image,180);elseif($orientation===4)imageflip($image,IMG_FLIP_VERTICAL);elseif($orientation===5){imageflip($image,IMG_FLIP_HORIZONTAL);$image=$this->rotateImage($image,90);}elseif($orientation===6)$image=$this->rotateImage($image,270);elseif($orientation===7){imageflip($image,IMG_FLIP_HORIZONTAL);$image=$this->rotateImage($image,270);}elseif($orientation===8)$image=$this->rotateImage($image,90);if(!$image)throw new MediaProcessingValidationException('JPEG orientation normalization failed.');return $image;}
    private function crop($image,array $crop){$w=imagesx($image);$h=imagesy($image);if($crop['x']+$crop['width']>$w||$crop['y']+$crop['height']>$h)throw new MediaProcessingValidationException('Crop bounds are invalid.');return $this->copy($image,$crop['width'],$crop['height'],$crop['x'],$crop['y'],$crop['width'],$crop['height']);}
    private function aspectCrop($image,array $ratio){$w=imagesx($image);$h=imagesy($image);$target=$ratio['width']/$ratio['height'];$current=$w/$h;if($current>$target){$cw=max(1,(int)floor($h*$target));$x=(int)floor(($w-$cw)/2);return $this->copy($image,$cw,$h,$x,0,$cw,$h);} $ch=max(1,(int)floor($w/$target));$y=(int)floor(($h-$ch)/2);return $this->copy($image,$w,$ch,0,$y,$w,$ch);}
    private function resize($image,?int $width,?int $height,string $fit){$sw=imagesx($image);$sh=imagesy($image);if($width===null)$width=max(1,(int)round($sw*$height/$sh));if($height===null)$height=max(1,(int)round($sh*$width/$sw));if($width>$sw||$height>$sh)throw new MediaProcessingValidationException('Upscaling is not allowed.');if($fit==='cover'){ $scale=max($width/$sw,$height/$sh);$cw=max($width,(int)round($width/$scale));$ch=max($height,(int)round($height/$scale));$crop=$this->copy($image,$cw,$ch,(int)floor(($sw-$cw)/2),(int)floor(($sh-$ch)/2),$cw,$ch);$image=$crop;}elseif($fit==='contain'){ $scale=min($width/$sw,$height/$sh);$width=max(1,(int)floor($sw*$scale));$height=max(1,(int)floor($sh*$scale));}return $this->copy($image,$width,$height,0,0,imagesx($image),imagesy($image));}
    private function copy($source,int $width,int $height,int $srcX,int $srcY,?int $srcWidth=null,?int $srcHeight=null){$this->validateBounds($width,$height);$srcWidth??=imagesx($source);$srcHeight??=imagesy($source);$target=imagecreatetruecolor($width,$height);if(!$target)throw new MediaProcessingCapabilityException('Image processing allocation failed.');imagealphablending($target,false);imagesavealpha($target,true);$transparent=imagecolorallocatealpha($target,0,0,0,127);imagefill($target,0,0,$transparent);if(!imagecopyresampled($target,$source,0,0,$srcX,$srcY,$width,$height,$srcWidth,$srcHeight))throw new MediaProcessingValidationException('Image processing failed.');return $target;}
    private function rotate($image,int $degrees){$angle=$degrees===90?270:($degrees===270?90:$degrees);$result=$this->rotateImage($image,$angle);if(!$result)throw new MediaProcessingValidationException('Image rotation failed.');return $result;}
    private function rotateImage($image,int $angle){$transparent=imagecolorallocatealpha($image,0,0,0,127);$result=imagerotate($image,$angle,$transparent);if($result){imagealphablending($result,false);imagesavealpha($result,true);}return $result;}
    private function prepareAlpha($image,string $format){if($format==='jpg'){ $bg=imagecreatetruecolor(imagesx($image),imagesy($image));$white=imagecolorallocate($bg,255,255,255);imagefill($bg,0,0,$white);imagecopy($bg,$image,0,0,0,0,imagesx($image),imagesy($image));imagedestroy($image);return $bg;}return $image;}
    private function encode($image,string $path,string $format,?int $quality):void{$ok=$format==='jpg'?imagejpeg($image,$path,$quality??85):($format==='png'?imagepng($image,$path,self::PNG_COMPRESSION):imagewebp($image,$path,$quality??82));if(!$ok||!is_file($path))throw new MediaProcessingStorageException('Generated image could not be encoded.');}
    private function validateBounds(int $width,int $height):void{if($width<1||$height<1||$width>self::MAX_WIDTH||$height>self::MAX_HEIGHT||$width*$height>self::MAX_PIXELS)throw new MediaProcessingValidationException('Generated image bounds are invalid.');}
    private function preflight(MediaProcessingFacts $facts, MediaProcessingRequest $request): void { $limit=$this->memoryLimit(); if($limit===null)return; $targetPixels=$facts->pixels(); if($request->resizeWidth()!==null)$targetPixels=min($targetPixels,$request->resizeWidth()*($request->resizeHeight()??max(1,(int)round($facts->height()*$request->resizeWidth()/$facts->width())))); $estimate=($facts->pixels()+$targetPixels+max($facts->width(),$facts->height())**2)*4*2; if(memory_get_usage(true)+$estimate>$limit*0.70)throw new MediaProcessingCapabilityException('Image processing memory budget is unavailable.'); }
    private function memoryLimit(): ?int { $value=ini_get('memory_limit'); if($value===false||$value===''||$value==='-1')return null; $unit=strtolower(substr($value,-1));$number=(float)$value;return (int)($number*(['g'=>1073741824,'m'=>1048576,'k'=>1024][$unit]??1)); }
    private function mime(string $format):string{return ['jpg'=>'image/jpeg','png'=>'image/png','webp'=>'image/webp'][$format];}
}
