<?php

use Copot\Core\Database;

final class MediaProcessingService
{
    public function __construct(private Database $database, private MediaRepository $media, private MediaVariantRepository $variants, private MediaFileInspector $inspector, private MediaImageProcessor $processor, private MediaFilesystemStorage $originalStorage, private MediaVariantFilesystemStorage $storage, private $diagnostics = null) {}

    public function process(MediaId|int $mediaId, MediaProcessingRequest $request): array
    {
        $mediaId = $mediaId instanceof MediaId ? $mediaId : new MediaId($mediaId); if ($request->sourceId()->value() !== $mediaId->value()) throw new MediaProcessingValidationException('Processing source does not match the Media identity.');
        $media = $this->media->findById($mediaId); if (!$media) throw new MediaProcessingValidationException('Media was not found.'); if ($media->kind() !== 'image' || !in_array($media->mimeType(), ['image/jpeg','image/png','image/webp'], true)) throw new MediaProcessingValidationException('Media format is not editable.');
        $original = $this->originalPath($media); $sourceInspection = $this->inspector->inspect($original); if ($sourceInspection->mimeType() !== $media->mimeType() || $sourceInspection->extension() !== $media->extension() || $sourceInspection->byteSize() !== $media->byteSize() || $sourceInspection->width() !== $media->width() || $sourceInspection->height() !== $media->height()) throw new MediaProcessingValidationException('Original Media facts do not match.');
        if ($request->crop() !== null && $request->cropAspectRatio() !== null) { $ratio = $request->cropAspectRatio(); if (abs(($request->crop()['width'] / $request->crop()['height']) - ($ratio['width'] / $ratio['height'])) > 0.01) throw new MediaProcessingValidationException('Crop aspect ratio is invalid.'); }
        $requests=$this->requests($request,$original,$sourceInspection);$results=[];foreach($requests as $one){$results[]=$this->processOne($media,$original,$sourceInspection,$one);}return $results;
    }

    private function processOne(Media $media,string $original,MediaUploadInspection $source,MediaProcessingRequest $request): MediaVariant
    {
        $format=$request->outputFormat()??$source->extension();$semantic=$request->semanticKey();$physical=MediaVariantKey::physical($media->id(),$media->storageKey(),$semantic,$this->processor->processorVersion(),$format);$existing=$this->variants->find($media->id(),$semantic);$existingPath=$this->storage->resolve($physical);
        if($existing&&$existing->storageKey()===$physical&&$existingPath){$facts=$this->facts($existingPath);if($facts->mimeType()===$existing->mimeType()&&$facts->extension()===$existing->extension()&&$facts->byteSize()===$existing->byteSize()&&$facts->width()===$existing->width()&&$facts->height()===$existing->height())return $existing;}
        $staged=$this->storage->stageGenerated(fn(string $path): MediaProcessingFacts=>$this->processor->write($original,$path,$this->toFacts($source),$request));$outputFacts=null;try{$outputFacts=$this->facts($staged->path());if($outputFacts->extension()!==$format)throw new MediaProcessingValidationException('Generated output format is invalid.');$already=$existingPath!==null;$created=false;if($already){$existingFacts=$this->facts($existingPath);if(!$existingFacts->same($outputFacts))throw new MediaProcessingStorageException('Existing variant output does not match.');$this->storage->discard($staged);}else{$this->storage->activate($staged,$physical);$created=true;$staged=null;}$connection=$this->database->connection();$connection->beginTransaction();try{$previous=$this->variants->saveOrReplaceDescriptor(['media_id'=>$media->id()->value(),'variant_key'=>$semantic,'storage_key'=>$physical,'mime_type'=>$outputFacts->mimeType(),'extension'=>$outputFacts->extension(),'byte_size'=>$outputFacts->byteSize(),'width'=>$outputFacts->width(),'height'=>$outputFacts->height()]);$connection->commit();}catch(Throwable $e){if($connection->inTransaction())$connection->rollBack();throw $e;}if($previous&&$previous->storageKey()!==$physical){try{$this->storage->delete($previous->storageKey());}catch(Throwable){$this->warnCleanup();}}$saved=$this->variants->find($media->id(),$semantic);if(!$saved)throw new MediaProcessingStorageException('Generated variant was not persisted.');return $saved;}catch(Throwable $e){if($staged)$this->storage->discard($staged);if(isset($created)&&$created){try{$this->storage->delete($physical);}catch(Throwable){$this->warnCleanup();}}if($e instanceof MediaProcessingException)throw $e;throw new MediaProcessingStorageException('Generated variant could not be stored.',0,$e);}
    }

    private function requests(MediaProcessingRequest $request,string $path,MediaUploadInspection $source): array { $widths=$request->responsiveWidths();if($widths===[]){$this->validateRequestBounds($request);return[$request];}$effective=$this->processor->normalizedDimensions($path,$this->toFacts($source))[0];$requests=[];foreach($widths as $width){if($width>$effective)continue;$candidate=$request->forWidth($width);$this->validateRequestBounds($candidate);$requests[$candidate->semanticKey()]=$candidate;}if($requests===[])throw new MediaProcessingValidationException('No responsive output remains.');return array_values($requests);}
    private function validateRequestBounds(MediaProcessingRequest $request):void{foreach([$request->resizeWidth(),$request->resizeHeight()] as $value)if($value!==null&&$value>4096)throw new MediaProcessingValidationException('Requested output dimensions exceed the limit.');}
    private function originalPath(Media $media):string{if(!preg_match('/^[a-f0-9]{32}\.(jpg|png|webp)$/',$media->storageKey()))throw new MediaProcessingValidationException('Original storage identity is invalid.');$path=$this->originalStorage->resolve($media->storageKey());if(!$path)throw new MediaProcessingValidationException('Original Media is unavailable.');return $path;}
    private function facts(string $path): MediaProcessingFacts{$f=$this->inspector->inspect($path);if($f->width()===null||$f->height()===null)throw new MediaProcessingValidationException('Generated image dimensions are invalid.');return new MediaProcessingFacts($f->mimeType(),$f->extension(),$f->byteSize(),$f->width(),$f->height());}
    private function toFacts(MediaUploadInspection $f): MediaProcessingFacts{return new MediaProcessingFacts($f->mimeType(),$f->extension(),$f->byteSize(),$f->width()??0,$f->height()??0);}
    private function warnCleanup():void{if(is_object($this->diagnostics)&&method_exists($this->diagnostics,'warning'))$this->diagnostics->warning('media.variant_cleanup_failed','Generated variant cleanup failed.',['component'=>'media']);}
}
