<?php
$adminUrl=is_callable($adminUrl??null)?$adminUrl:static fn(string $path=''):string=>'/'.trim($path,'/');$workspace=is_array($workspace??null)?$workspace:[];$items=$workspace['items']??[];$filters=is_array($filters??null)?$filters:[];$noticeMessages=['created'=>'Form created successfully.','updated'=>'Form updated successfully.','published'=>'Form published successfully.','disabled'=>'Form disabled successfully.','deleted'=>'Form deleted successfully.'];$notice=is_scalar($notice??null)?($noticeMessages[(string)$notice]??null):null;$error=is_scalar($error??null)?(string)$error:'';$page=(int)($filters['page']??1);$perPage=(int)($filters['per_page']??25);$total=(int)($workspace['total']??0);$pages=max(1,(int)ceil($total/max(1,$perPage)));$query=static function(int $target)use($filters):string{$parameters=array_filter(['q'=>$filters['q']??null,'status'=>$filters['status']??null,'per_page'=>$filters['per_page']??null,'page'=>$target],static fn($value)=>$value!==null&&$value!=='');return http_build_query($parameters);};
?>
<section class="admin-content-page" aria-labelledby="form-list-title">
 <header class="admin-content-header"><div class="admin-content-header__copy"><p class="admin-content-eyebrow">Form Manager</p><h2 id="form-list-title">Forms</h2><p>Manage reusable form definitions and their lifecycle.</p></div><div class="admin-actions"><?php if(!empty($canViewSubmissions)):?><a class="admin-button admin-button--secondary" href="<?=htmlspecialchars($adminUrl('forms/submissions'),ENT_QUOTES,'UTF-8')?>">View submissions</a><?php endif;?><?php if(!empty($canManage)):?><a class="admin-button admin-button--primary" href="<?=htmlspecialchars($adminUrl('forms/create'),ENT_QUOTES,'UTF-8')?>">Create Form</a><?php endif;?></div></header>
 <?php if($notice):?><div class="admin-alert admin-alert--success" role="status"><?=htmlspecialchars($notice,ENT_QUOTES,'UTF-8')?></div><?php endif;?><?php if($error!==''):?><div class="admin-alert admin-alert--danger" role="alert"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></div><?php endif;?>
 <section class="admin-panel admin-content-table-panel" aria-labelledby="form-workspace-title"><header class="admin-content-table-panel__header"><div><h3 id="form-workspace-title">Form definitions</h3><p><?= $total ?> form<?= $total===1?'':'s' ?>.</p></div></header>
  <form class="admin-form" method="get" action="<?=htmlspecialchars($workspaceUrl??$adminUrl('forms'),ENT_QUOTES,'UTF-8')?>"><div class="admin-field"><label class="admin-field__label" for="form-search">Search forms</label><input id="form-search" name="q" type="search" value="<?=htmlspecialchars((string)($filters['q']??''),ENT_QUOTES,'UTF-8')?>"></div><div class="admin-field"><label class="admin-field__label" for="form-status">Status</label><select id="form-status" name="status"><option value="">All statuses</option><?php foreach(FormDefinitionValidator::FORM_STATES as $state):?><option value="<?=$state?>" <?=($filters['status']??null)===$state?'selected':''?>><?=htmlspecialchars(ucfirst($state),ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></div><div class="admin-field"><label class="admin-field__label" for="form-per-page">Per page</label><input id="form-per-page" name="per_page" type="number" min="1" max="100" value="<?=htmlspecialchars((string)$perPage,ENT_QUOTES,'UTF-8')?>"></div><div class="admin-actions"><button class="admin-button admin-button--secondary" type="submit">Apply filters</button></div></form>
  <?php if($items===[]):?><div class="admin-empty-state"><h3 class="admin-empty-state__title">No forms found</h3><p class="admin-empty-state__description">Create a form or adjust the workspace filters.</p></div><?php else:?><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th scope="col">Name</th><th scope="col">Status</th><th scope="col">Updated</th><?php if(!empty($canManage)):?><th scope="col">Actions</th><?php endif;?></tr></thead><tbody><?php foreach($items as $form):$retained=is_callable($hasSubmissions??null)&&$hasSubmissions($form);?><tr><td data-label="Name"><?=htmlspecialchars($form->name(),ENT_QUOTES,'UTF-8')?></td><td data-label="Status"><?=htmlspecialchars(ucfirst($form->status()),ENT_QUOTES,'UTF-8')?></td><td data-label="Updated"><?=htmlspecialchars($form->updatedAt(),ENT_QUOTES,'UTF-8')?></td><?php if(!empty($canManage)):?><td data-label="Actions"><div class="admin-actions"><a class="admin-button admin-button--link" href="<?=htmlspecialchars($adminUrl('forms/'.$form->id()->value().'/edit'),ENT_QUOTES,'UTF-8')?>">Edit</a><?php if($form->status()==='draft'):?><form method="post" action="<?=htmlspecialchars($adminUrl('forms/'.$form->id()->value().'/publish'),ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="_token" value="<?=htmlspecialchars((string)($csrfToken??''),ENT_QUOTES,'UTF-8')?>"><button class="admin-button admin-button--link" type="submit">Publish</button></form><?php endif;?><?php if(in_array($form->status(),['draft','published'],true)):?><form method="post" action="<?=htmlspecialchars($adminUrl('forms/'.$form->id()->value().'/disable'),ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="_token" value="<?=htmlspecialchars((string)($csrfToken??''),ENT_QUOTES,'UTF-8')?>"><button class="admin-button admin-button--link" type="submit">Disable</button></form><?php endif;?><?php if(!$retained):?><form method="post" action="<?=htmlspecialchars($adminUrl('forms/'.$form->id()->value().'/delete'),ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="_token" value="<?=htmlspecialchars((string)($csrfToken??''),ENT_QUOTES,'UTF-8')?>"><button class="admin-button admin-button--link" type="submit">Delete form permanently</button></form><?php else:?><span>This form has retained submissions and cannot be deleted. Disable it instead.</span><?php endif;?></div></td><?php endif;?></tr><?php endforeach;?></tbody></table></div><?php endif;?>
  <?php if($pages>1):?><nav class="admin-actions" aria-label="Form pagination"><?php if($page>1):?><a class="admin-button admin-button--secondary" href="<?=htmlspecialchars(($workspaceUrl??$adminUrl('forms')).'?'.$query($page-1),ENT_QUOTES,'UTF-8')?>">Previous</a><?php endif;?><span>Page <?=$page?> of <?=$pages?></span><?php if($page<$pages):?><a class="admin-button admin-button--secondary" href="<?=htmlspecialchars(($workspaceUrl??$adminUrl('forms')).'?'.$query($page+1),ENT_QUOTES,'UTF-8')?>">Next</a><?php endif;?></nav><?php endif;?>
 </section>
</section>
