<?php
namespace Copot\Core;
require_once __DIR__ . '/MediaUploadExceptions.php';
use PDO;
final class MediaRepository{
 public function __construct(private Database $database){} private function table():string{return $this->database->table('media');}
 public function findById(MediaId|int $id,bool $forUpdate=false):?Media{$id=$id instanceof MediaId?$id:new MediaId($id);$s=$this->database->connection()->prepare('SELECT * FROM '.$this->table().' WHERE id=:id LIMIT 1'.($forUpdate?' FOR UPDATE':''));$s->execute(['id'=>$id->value()]);$r=$s->fetch();return is_array($r)?$this->hydrate($r):null;}
 public function findByStorageKey(string $key):?Media{$s=$this->database->connection()->prepare('SELECT * FROM '.$this->table().' WHERE storage_key=:k LIMIT 1');$s->execute(['k'=>$key]);$r=$s->fetch();return is_array($r)?$this->hydrate($r):null;}
 public function paginate(string $kind='',int $limit=50,int $offset=0):array{$limit=max(1,min($limit,100));$offset=max(0,$offset);$w=$kind===''?'':' WHERE kind=:kind';$s=$this->database->connection()->prepare('SELECT * FROM '.$this->table().$w.' ORDER BY updated_at DESC,id DESC LIMIT :l OFFSET :o');if($kind!=='')$s->bindValue('kind',$kind);$s->bindValue('l',$limit,PDO::PARAM_INT);$s->bindValue('o',$offset,PDO::PARAM_INT);$s->execute();return array_map(fn(array $r):Media=>$this->hydrate($r),$s->fetchAll());}
 public function workspace(array $f=[],int $limit=24,int $offset=0):array{$limit=max(1,min($limit,24));$offset=max(0,$offset);$w=[];$p=[];$q=trim((string)($f['search']??''));if($q!==''){$w[]='(title LIKE :q OR original_filename LIKE :f)';$p=['q'=>'%'.$q.'%','f'=>'%'.$q.'%'];}$k=$f['kind']??null;if(in_array($k,['image','document'],true)){$w[]='kind=:kind';$p['kind']=$k;}$capability=$f['capability']??null;$editable="(kind='image' AND mime_type IN ('image/jpeg','image/png','image/webp'))";if($capability==='editable')$w[]=$editable;elseif($capability==='manage-only')$w[]='NOT '.$editable;$where=$w===[]?'':' WHERE '.implode(' AND ',$w);$c=$this->database->connection();$count=$c->prepare('SELECT COUNT(*) FROM '.$this->table().$where);$count->execute($p);$s=$c->prepare('SELECT * FROM '.$this->table().$where.' ORDER BY updated_at DESC,id DESC LIMIT :l OFFSET :o');foreach($p as $n=>$v)$s->bindValue($n,$v);$s->bindValue('l',$limit,PDO::PARAM_INT);$s->bindValue('o',$offset,PDO::PARAM_INT);$s->execute();return ['items'=>array_map(fn(array $r):Media=>$this->hydrate($r),$s->fetchAll()),'total'=>(int)$count->fetchColumn(),'limit'=>$limit,'offset'=>$offset];}
 public function create(array $d):MediaId{$s=$this->database->connection()->prepare('INSERT INTO '.$this->table().' (kind,original_filename,title,storage_key,mime_type,extension,byte_size,width,height,created_at,updated_at) VALUES (:kind,:original_filename,:title,:storage_key,:mime_type,:extension,:byte_size,:width,:height,NOW(),NOW())');$s->execute($d);return new MediaId((int)$this->database->connection()->lastInsertId());}
 public function updateTitle(MediaId|int $id,string $title):void{$id=$id instanceof MediaId?$id:new MediaId($id);$s=$this->database->connection()->prepare('UPDATE '.$this->table().' SET title=:title,updated_at=GREATEST(NOW(),DATE_ADD(updated_at,INTERVAL 1 SECOND)) WHERE id=:id');$s->execute(['id'=>$id->value(),'title'=>$title]);if($s->rowCount()!==1)throw new MediaNotFoundException('Media could not be updated.');}
 public function delete(MediaId|int $id):void{$id=$id instanceof MediaId?$id:new MediaId($id);$s=$this->database->connection()->prepare('DELETE FROM '.$this->table().' WHERE id=:id');$s->execute(['id'=>$id->value()]);if($s->rowCount()!==1)throw new MediaNotFoundException('Media could not be deleted.');}
 private function hydrate(array $r):Media{return new Media(new MediaId((int)$r['id'],), (string)$r['kind'],(string)$r['original_filename'],(string)$r['title'],(string)$r['storage_key'],(string)$r['mime_type'],(string)$r['extension'],(int)$r['byte_size'],$r['width']===null?null:(int)$r['width'],$r['height']===null?null:(int)$r['height'],(string)$r['created_at'],(string)$r['updated_at']);}
}
