<?php

namespace Copot\Core;

final class ModuleLifecycleOperationStore
{
    private string $root; private string $path;
    public function __construct(string $storagePath) { if (!is_dir($storagePath)||is_link($storagePath)||!is_writable($storagePath)) throw new \RuntimeException('Module operation storage is unavailable.'); $storage=realpath($storagePath); if($storage===false) throw new \RuntimeException('Module operation storage is unavailable.'); $this->root=$storage.DIRECTORY_SEPARATOR.'.copot-lifecycle'; if(!is_dir($this->root)&&!mkdir($this->root,0700,true)) throw new \RuntimeException('Module operation storage could not be created.'); if(is_link($this->root)||!is_dir($this->root)||!is_writable($this->root)) throw new \RuntimeException('Module operation storage is invalid.'); $this->path=$this->root.DIRECTORY_SEPARATOR.'module-operation.json'; }
    public function read(): ?ModuleLifecycleOperationRecord { if(!file_exists($this->path)) return null; if(is_link($this->path)||!is_file($this->path)||!is_readable($this->path)) throw new \RuntimeException('Module lifecycle operation is invalid.'); try { $data=json_decode((string)file_get_contents($this->path),true,16,JSON_THROW_ON_ERROR); return ModuleLifecycleOperationRecord::fromArray($data); } catch(\Throwable $e){ throw new \RuntimeException('Module lifecycle operation is invalid.',0,$e); } }
    public function create(ModuleLifecycleOperationRecord $record): void { if($this->read()!==null) throw new \RuntimeException('A Module lifecycle operation is already active.'); $this->write($record,false); }
    public function save(ModuleLifecycleOperationRecord $record): void { $current=$this->read(); if(!$current instanceof ModuleLifecycleOperationRecord||$current->operationId()!==$record->operationId()) throw new \RuntimeException('Module lifecycle operation identity changed.'); $this->write($record,true); }
    public function clear(ModuleLifecycleOperationRecord $record): void { $current=$this->read(); if(!$current instanceof ModuleLifecycleOperationRecord||$current->operationId()!==$record->operationId()||!$record->isTerminal()) throw new \RuntimeException('Module lifecycle operation cannot be cleared.'); if(is_link($this->path)||!@unlink($this->path)) throw new \RuntimeException('Module lifecycle operation could not be cleared.'); }
    private function write(ModuleLifecycleOperationRecord $record,bool $replace): void { $tmp=$this->root.DIRECTORY_SEPARATOR.'.module-operation-'.bin2hex(random_bytes(8)).'.tmp'; $h=@fopen($tmp,'xb'); if(!is_resource($h)) throw new \RuntimeException('Module operation could not be prepared.'); try{$contents=json_encode($record->toArray(),JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES).PHP_EOL; if(@fwrite($h,$contents)!==strlen($contents)||!@fflush($h)) throw new \RuntimeException('Module operation could not be finalized.');}finally{fclose($h);} @chmod($tmp,0600); if(!$replace&&file_exists($this->path)){@unlink($tmp);throw new \RuntimeException('A Module lifecycle operation is already active.');} if(!@rename($tmp,$this->path)){@unlink($tmp);throw new \RuntimeException('Module operation could not be activated.');} }
}
