<?php

namespace Copot\Core;

final class ModuleLifecycleOperationRecord
{
    public const PREPARING = 'preparing'; public const APPLYING = 'applying'; public const MIGRATING = 'migrating'; public const FINALIZING = 'finalizing'; public const BLOCKED = 'blocked'; public const INDETERMINATE = 'indeterminate'; public const CLEANUP_PENDING = 'cleanup_pending'; public const COMPLETED = 'completed';
    private const PHASES = [self::PREPARING,self::APPLYING,self::MIGRATING,self::FINALIZING,self::BLOCKED,self::INDETERMINATE,self::CLEANUP_PENDING,self::COMPLETED];
    public function __construct(private string $operationId, private ModuleIdentity $module, private string $classification, private string $packageIdentity, private string $packageVersion, private string $releaseIdentity, private string $archiveSha256, private string $stagingPath, private string $applyPlanIdentity, private string $phase, private int $fileCursor, private ?string $lastVerifiedPath, private string $migrationStateIdentity, private ?string $committedStateIdentity, private string $createdAt, private string $updatedAt, private string $reason = '')
    {
        foreach ([$operationId,$packageIdentity,$releaseIdentity,$archiveSha256,$stagingPath,$applyPlanIdentity,$migrationStateIdentity,$createdAt,$updatedAt] as $value) if ($value === '' || trim($value) !== $value) throw new \InvalidArgumentException('Module lifecycle operation identity is invalid.');
        PackageVersion::assertValid($packageVersion); ModuleIdentity::assertValid($module->value());
        foreach (['archive' => $archiveSha256, 'apply' => $applyPlanIdentity] as $label => $hash) if (!preg_match('/^[a-f0-9]{64}$/', $hash)) throw new \InvalidArgumentException('Module operation ' . $label . ' identity is invalid.');
        if (!in_array($phase, self::PHASES, true) || $fileCursor < 0) throw new \InvalidArgumentException('Module lifecycle operation phase is invalid.');
    }
    public function operationId(): string { return $this->operationId; } public function module(): ModuleIdentity { return $this->module; } public function classification(): string { return $this->classification; } public function packageIdentity(): string { return $this->packageIdentity; } public function packageVersion(): string { return $this->packageVersion; } public function releaseIdentity(): string { return $this->releaseIdentity; } public function archiveSha256(): string { return $this->archiveSha256; } public function stagingPath(): string { return $this->stagingPath; } public function applyPlanIdentity(): string { return $this->applyPlanIdentity; } public function phase(): string { return $this->phase; } public function fileCursor(): int { return $this->fileCursor; } public function lastVerifiedPath(): ?string { return $this->lastVerifiedPath; } public function migrationStateIdentity(): string { return $this->migrationStateIdentity; } public function committedStateIdentity(): ?string { return $this->committedStateIdentity; } public function reason(): string { return $this->reason; }
    public function isTerminal(): bool { return in_array($this->phase, [self::BLOCKED,self::INDETERMINATE,self::COMPLETED,self::CLEANUP_PENDING], true); }
    public function bindMigrationStateIdentity(string $identity): self { if ($identity === '' || trim($identity) !== $identity) throw new \InvalidArgumentException('Module migration state identity is invalid.'); return new self($this->operationId,$this->module,$this->classification,$this->packageIdentity,$this->packageVersion,$this->releaseIdentity,$this->archiveSha256,$this->stagingPath,$this->applyPlanIdentity,$this->phase,$this->fileCursor,$this->lastVerifiedPath,$identity,$this->committedStateIdentity,$this->createdAt,gmdate(DATE_ATOM),$this->reason); }
    public function advance(string $phase, int $cursor, ?string $lastPath = null, ?string $committedIdentity = null, string $reason = ''): self { return new self($this->operationId,$this->module,$this->classification,$this->packageIdentity,$this->packageVersion,$this->releaseIdentity,$this->archiveSha256,$this->stagingPath,$this->applyPlanIdentity,$phase,$cursor,$lastPath ?? $this->lastVerifiedPath,$this->migrationStateIdentity,$committedIdentity ?? $this->committedStateIdentity,$this->createdAt,gmdate(DATE_ATOM),$reason); }
    public function toArray(): array { return ['operation_id'=>$this->operationId,'module'=>$this->module->value(),'classification'=>$this->classification,'package_identity'=>$this->packageIdentity,'package_version'=>$this->packageVersion,'release_identity'=>$this->releaseIdentity,'archive_sha256'=>$this->archiveSha256,'staging_path'=>$this->stagingPath,'apply_plan_identity'=>$this->applyPlanIdentity,'phase'=>$this->phase,'file_cursor'=>$this->fileCursor,'last_verified_path'=>$this->lastVerifiedPath,'migration_state_identity'=>$this->migrationStateIdentity,'committed_state_identity'=>$this->committedStateIdentity,'created_at'=>$this->createdAt,'updated_at'=>$this->updatedAt,'reason'=>$this->reason]; }
    public static function fromArray(array $data): self { $keys=['operation_id','module','classification','package_identity','package_version','release_identity','archive_sha256','staging_path','apply_plan_identity','phase','file_cursor','last_verified_path','migration_state_identity','committed_state_identity','created_at','updated_at','reason']; if (array_keys($data)!==$keys) throw new \InvalidArgumentException('Module lifecycle operation format is invalid.'); return new self((string)$data['operation_id'],new ModuleIdentity((string)$data['module']),(string)$data['classification'],(string)$data['package_identity'],(string)$data['package_version'],(string)$data['release_identity'],(string)$data['archive_sha256'],(string)$data['staging_path'],(string)$data['apply_plan_identity'],(string)$data['phase'],(int)$data['file_cursor'],$data['last_verified_path']===null?null:(string)$data['last_verified_path'],(string)$data['migration_state_identity'],$data['committed_state_identity']===null?null:(string)$data['committed_state_identity'],(string)$data['created_at'],(string)$data['updated_at'],(string)$data['reason']); }
}
