<?php

namespace Copot\Core;

use PDO;

final class ModuleApplyCoordinator
{
    public function __construct(private InstallationMutex $mutex, private ModuleLifecycleOperationStore $operations, private PackageOwnedFileApplier $applier, private ModuleLifecycleStateStore $states, private ModuleTargetIntegrityVerifier $integrity, private string $liveRoot) {}

    /** @param callable(PDO,ModuleTransitionPlan,ModulePackageInspection):ModuleMigrationReconciliationResult $migrationRunner @param callable(ModuleTransitionPlan,ModulePackageInspection):ModuleProvisioningReconciliationResult $provisioningRunner @param callable(ModuleTransitionPlan,ModulePackageInspection):ModulePermissionReconciliationResult $permissionRunner */
    public function execute(ModulePackageInspection $inspection, ModuleTransitionPlan $transition, ModuleDependencyConflictPlan $conflicts, PDO $connection, callable $migrationRunner, callable $provisioningRunner, callable $permissionRunner, ?callable $moduleHealthProbe = null): ModuleApplyResult
    {
        $lock=$this->mutex->acquire(); if(!$lock instanceof InstallationLock) return new ModuleApplyResult(ModuleApplyResult::BLOCKED,'Another lifecycle operation is already running.');
        $record = null;
        try {
            $existing=$this->operations->read(); if($existing instanceof ModuleLifecycleOperationRecord && $existing->phase()===ModuleLifecycleOperationRecord::CLEANUP_PENDING) return $this->retryCleanupLocked($existing,$inspection,$transition);
            if($existing instanceof ModuleLifecycleOperationRecord) return new ModuleApplyResult(ModuleApplyResult::BLOCKED,'A Module lifecycle operation is already active.',$existing->operationId());
            $contract=$inspection->contract(); $target=$transition->target();
            if ($target->contract()->moduleIdentity()->value() !== $contract->moduleIdentity()->value() || $target->contract()->packageIdentity()->value() !== $contract->packageIdentity()->value()) return new ModuleApplyResult(ModuleApplyResult::FAILED,'Inspection and transition target identities do not match.');
            if(!$transition->accepted()) return new ModuleApplyResult(ModuleApplyResult::FAILED,$transition->reason());
            if(!$conflicts->accepted() || $conflicts->target()->contract()->moduleIdentity()->value()!==$contract->moduleIdentity()->value()) return new ModuleApplyResult(ModuleApplyResult::FAILED,'Dependency/conflict plan is not accepted for this Module target.');
            $this->assertOwnedPayload($inspection);
            $plan=WebcoreApplyPlan::fromPayload($inspection->livePayload());
            $operationId=bin2hex(random_bytes(16)); $pendingMigration=hash('sha256','pending:'.$contract->moduleIdentity()->value()); $now=gmdate(DATE_ATOM);
            $record=new ModuleLifecycleOperationRecord($operationId,$contract->moduleIdentity(),$transition->classification(),$contract->packageIdentity()->value(),$contract->packageVersion(),$contract->releaseIdentity(),$inspection->livePayload()->archiveSha256(),$inspection->livePayload()->stagingPath(),$plan->identity(),ModuleLifecycleOperationRecord::PREPARING,0,null,$pendingMigration,null,$now,$now);
            $this->operations->create($record);
            if(!$this->save($record->advance(ModuleLifecycleOperationRecord::APPLYING,0))) return new ModuleApplyResult(ModuleApplyResult::BLOCKED,'Module operation could not enter apply state.',$operationId);
            $applied=[]; $apply=$this->applier->apply($plan,function(int $cursor,string $path) use (&$record,&$applied):void{$applied[]=$path;$record=$record->advance(ModuleLifecycleOperationRecord::APPLYING,$cursor,$path);$this->operations->save($record);});
            $applied=$apply->appliedPaths();
            if($apply->status()!==WebcoreApplyResult::COMPLETED){$phase=$applied===[]?ModuleLifecycleOperationRecord::BLOCKED:ModuleLifecycleOperationRecord::BLOCKED;$this->operations->save($record->advance($phase,count($applied),$applied===[]?null:$applied[count($applied)-1],null,$apply->reason()));return new ModuleApplyResult(ModuleApplyResult::BLOCKED,$apply->reason(),$operationId,$applied);}
            $record=$record->advance(ModuleLifecycleOperationRecord::MIGRATING,count($applied),$applied===[]?null:$applied[count($applied)-1]);$this->operations->save($record);
            $migration=$migrationRunner($connection,$transition,$inspection);
            if(!$migration instanceof ModuleMigrationReconciliationResult){$this->operations->save($record->advance(ModuleLifecycleOperationRecord::INDETERMINATE,count($applied),null,null,'Module migration outcome is indeterminate.'));return new ModuleApplyResult(ModuleApplyResult::INDETERMINATE,'Module migration outcome is indeterminate.',$operationId,$applied);}
            if($migration->status()===ModuleMigrationReconciliationResult::INDETERMINATE){$this->operations->save($record->advance(ModuleLifecycleOperationRecord::INDETERMINATE,count($applied),null,null,$migration->reason()));return new ModuleApplyResult(ModuleApplyResult::INDETERMINATE,$migration->reason(),$operationId,$applied);}
            if(!in_array($migration->status(),[ModuleMigrationReconciliationResult::COMPLETED,ModuleMigrationReconciliationResult::NOOP],true)) return $this->blocked($record,$migration->reason(),$applied,$operationId);
            if($migration->stateIdentity()==='') return $this->blocked($record,'Module migration state identity is unavailable.',$applied,$operationId);
            $record=$record->bindMigrationStateIdentity($migration->stateIdentity());$record=$record->advance(ModuleLifecycleOperationRecord::FINALIZING,count($applied));$this->operations->save($record);
            $provisioning=$provisioningRunner($transition,$inspection); if(!$provisioning instanceof ModuleProvisioningReconciliationResult||$provisioning->status()!==ModuleProvisioningReconciliationResult::COMPLETED) return $this->blocked($record,$provisioning instanceof ModuleProvisioningReconciliationResult?$provisioning->reason():'Provisioning outcome is invalid.',$applied,$operationId);
            $permissions=$permissionRunner($transition,$inspection); if(!$permissions instanceof ModulePermissionReconciliationResult||$permissions->status()!==ModulePermissionReconciliationResult::COMPLETED) return $this->blocked($record,$permissions instanceof ModulePermissionReconciliationResult?$permissions->reason():'Permission reconciliation outcome is invalid.',$applied,$operationId);
            $gates=$this->integrity->verify($inspection,new LiveTreePathGuard($this->liveRoot));
            $discovery=new ModuleDiscovery(rtrim($this->liveRoot,'/\\').DIRECTORY_SEPARATOR.'modules');$found=false;foreach($discovery->discover() as $module){if($module instanceof ModuleDefinition&&$module->name()===$contract->moduleIdentity()->value())$found=true;}$gates=new HealthGateMatrix(array_merge($gates->gates(),[$found?HealthGateResult::pass('module-discovery'):HealthGateResult::fail('module-discovery','Module discovery did not find the target Module.'),$discovery->errors()===[]?HealthGateResult::pass('module-bootstrap'):HealthGateResult::fail('module-bootstrap','Module discovery reported errors.')]));
            if($moduleHealthProbe!==null){$health=(bool)$moduleHealthProbe($inspection,$transition);$gates=new HealthGateMatrix(array_merge($gates->gates(),[$health?HealthGateResult::pass('module-contribution'):HealthGateResult::fail('module-contribution','Module contribution/load health failed.')]));}
            if(!$gates->passed()) return $this->blocked($record,$gates->failureReason(),$applied,$operationId,$gates);
            $state=new ModuleLifecycleState($contract->packageIdentity(),$contract->moduleIdentity(),$contract->packageVersion(),$contract->releaseIdentity(),$contract->contractVersion(),$migration->stateIdentity(),$target->packageIntegrityIdentity(),$transition->finalEnabled(),$transition->classification(),new \DateTimeImmutable('now'),$operationId);
            $this->states->write($state);$committedIdentity=hash('sha256',json_encode($state->toArray(),JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));$latest=$record->advance(ModuleLifecycleOperationRecord::COMPLETED,count($applied),$record->lastVerifiedPath(),$committedIdentity);try{$this->operations->clear($latest);}catch(\Throwable $e){$this->operations->save($latest->advance(ModuleLifecycleOperationRecord::CLEANUP_PENDING,count($applied),$latest->lastVerifiedPath(),$committedIdentity,'Committed Module state is complete; cleanup is pending.'));return new ModuleApplyResult(ModuleApplyResult::CLEANUP_PENDING,$e->getMessage(),$operationId,$applied,$gates);}return new ModuleApplyResult(ModuleApplyResult::COMPLETED,'',$operationId,$applied,$gates);
        } catch(\Throwable $e){if($record instanceof ModuleLifecycleOperationRecord){try{$this->operations->save($record->advance(ModuleLifecycleOperationRecord::BLOCKED,$record->fileCursor(),$record->lastVerifiedPath(),null,$e->getMessage()));}catch(\Throwable){}}return new ModuleApplyResult(ModuleApplyResult::BLOCKED,$e->getMessage(),$record?->operationId());} finally{$lock->release();}
    }

    private function retryCleanupLocked(ModuleLifecycleOperationRecord $record, ModulePackageInspection $inspection, ModuleTransitionPlan $transition): ModuleApplyResult { $contract=$inspection->contract(); if($record->module()->value()!==$contract->moduleIdentity()->value()||$record->packageIdentity()!==$contract->packageIdentity()->value()||$record->packageVersion()!==$contract->packageVersion()||$record->releaseIdentity()!==$contract->releaseIdentity()||!$transition->accepted()) return new ModuleApplyResult(ModuleApplyResult::FAILED,'Cleanup operation identity does not match the requested Module target.',$record->operationId()); $state=$this->states->read($record->module()); if(!$state instanceof ModuleLifecycleState||$record->committedStateIdentity()===null||hash('sha256',json_encode($state->toArray(),JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR))!==$record->committedStateIdentity()) return new ModuleApplyResult(ModuleApplyResult::BLOCKED,'Committed Module state does not match cleanup operation.',$record->operationId()); try{$this->operations->clear($record->advance(ModuleLifecycleOperationRecord::COMPLETED,$record->fileCursor(),$record->lastVerifiedPath(),$record->committedStateIdentity()));return new ModuleApplyResult(ModuleApplyResult::COMPLETED,'',$record->operationId());}catch(\Throwable $e){return new ModuleApplyResult(ModuleApplyResult::CLEANUP_PENDING,$e->getMessage(),$record->operationId());} }
    private function blocked(ModuleLifecycleOperationRecord $record,string $reason,array $applied,string $operationId,?HealthGateMatrix $gates=null): ModuleApplyResult {$this->operations->save($record->advance(ModuleLifecycleOperationRecord::BLOCKED,count($applied),$applied===[]?null:$applied[count($applied)-1],null,$reason));return new ModuleApplyResult(ModuleApplyResult::BLOCKED,$reason,$operationId,$applied,$gates);}
    private function save(ModuleLifecycleOperationRecord $record): bool { $this->operations->save($record); return true; }
    private function assertOwnedPayload(ModulePackageInspection $inspection): void { $root=$inspection->contract()->ownership()->rootPath();$prefix=$root.'/';foreach($inspection->livePayload()->files() as $file){if(!$file instanceof StagedFile||$file->path()===ModulePackageManifestReader::PATH||!str_starts_with($file->path(),$prefix))throw new \RuntimeException('Module apply payload escapes the owned Module root.');$segments=ArchiveEntryPath::segments($file->path());if(count($segments)<3||$segments[0]!=='modules'||$segments[1]!==$inspection->contract()->moduleIdentity()->value())throw new \RuntimeException('Module apply payload contains a cross-Module path.');}}
}
